project:
  type: book
  #always_allow_html: true
book:
  title: "To the lighthouse"
  author: "Des Ryan"
  date: "2022-23"
  
  chapters:
    - index.qmd
    - part: "**Part 1. The mild, non-Atlantic Way**"
      chapters:
      - ttl_01_poolbeg.qmd
      - ttl_02_north_bull.qmd
      - ttl_03_dun_laoghaire_1.qmd
      - ttl_04_howth_1.qmd
      - ttl_05_wicklow.qmd
      - ttl_06_balbriggan.qmd
      - ttl_07_drogheda.qmd
      - ttl_08_greenore.qmd
      - ttl_09_st_johns_point.qmd
      #- ttl_10_greencastle.qmd
      - ttl_11_dunmore_east_to_hook_head.qmd
      - ttl_12_rosslare_harbour.qmd
      - ttl_13_mine_head_youghal.qmd
      - ttl_15_dun_laoghaire_2.qmd
      - ttl_16_ballinacourty.qmd
      - ttl_17_dalkey.qmd
      #- ttl_18_duncannon.qmd
      #- ttl_19_ballycotton_rochespoint.qmd
      #- ttl_20_blackrock_castle_cobh.qmd      
      
    - part: "**Part 2. The Wild Atlantic Doris**"
      chapters:
      - ttl_14_black_head.qmd
  
bibliography: references.bib
format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt
editor: visual
