project:
  type: book
  #always_allow_html: true
book:
  title: "To the lighthouse"
  subtitle: "Vol 1: The Mild, non-Atlantic Way"
  author: "Des Ryan"
  reader-mode: true
  date: "August 2022"
  cover-image: images/cover_2025_02_26_IMG_20230729_090357_transplanted_bike.png
  #favicon: cover.jpg
  site-url: https://ggplot2-book.org/
  repo-url: https://github.com/hadley/ggplot2-book/
  repo-branch: master
  #repo-actions: [edit, issue]  
  page-footer:
    left: |
      To the lighthouse is an ongoing effort write about cycling to every lighthouse on or off the Island of Ireland
      written by Des Ryan and supported by you.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.  
  chapters:
    - index.qmd
    #- contents_creation.qmd
    - part: "**Part 1. The mild, non-Atlantic Way**"
      chapters:
      - ttl_01_poolbeg.qmd
      - ttl_02_north_bull.qmd
      - ttl_03_dun_laoghaire_1.qmd
      - ttl_04_howth_1.qmd
      - ttl_05_wicklow.qmd
      - ttl_06_balbriggan.qmd
      - ttl_07_drogheda.qmd
      - ttl_08_greenore.qmd
      - ttl_09_st_johns_point.qmd
      - ttl_10_haulbowline.qmd
      - ttl_11_dunmore_east_to_hook_head.qmd
      - ttl_12_rosslare_harbour.qmd
      - ttl_13_mine_head_youghal.qmd
      - ttl_15_dun_laoghaire_2.qmd
      - ttl_16_ballinacourty.qmd
      - ttl_17_dalkey.qmd
      - ttl_18_duncannon.qmd
      - ttl_19_ballycotton.qmd
      - ttl_20_roches_point.qmd
      - ttl_21_blackrock_castle_cobh.qmd      
      
    - part: "**Part 2. The Wild Atlantic Doris**"
      chapters:
      - ttl_14_black_head.qmd


format:
  pdf:
    documentclass: scrbook
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Des Ryann"
    #include-in-header: "ga_script.html"
    callout-appearance: simple
    
editor: visual


bibliography: references.bib
