---
title: "pitch"
---

**Notes for pitch**

-   A search for meaning

-   The meaning of lifehouses

    -   I like to think of meaning as something that operates within a system. Addition and subtraction mean something within numerical systems. Wage-labour means something within modern life because cash is the bloodflow of so many things we need.

    -   I need to get out and if I don't, I start to crack up.

    -   Cycling gets me out but I need a destination, a reason to keep going and to push through the sheer boredom of

    -   I can't go to the gym. I can't cope with the misery of being in pain while seeing nothing new. Novelty keeps me fresh.

    -   The first time I went out cycling, I went to explore Tallaght and then I saw the mountains and decided I had to go there. The allure of the visible target.

    -   A lighthouse is the perfect destination, a target past which you cannot go.

    -   Yeah you have to get back but you'll always do that because you hafta.

<!-- -->

-   Hook

    -   men's mental health

    -   a self-help book with no advice

    -   cycling, manhood, language, self-help, me time

    -   reflections on mental health and how to cope

    -   working out what is / was going on in this country

    -   slowly exploring Ireland's coast, one lighthouse at a time.

    -   Break free from quotidian

        -   *I decide to go directo(ish) to Fairview whence I can let the open air blow away the busyness of my midweek life and the clusterforked urbanscapes which host it*

        -   *the retreating seawater lures my space-craving soul into a crazed chase for freedom. I follow the coastal bike lane and feel the seabreeze on my face and my mind empties of thought for a moment or three.*

        -   *The sea takes you out of your world and without it, escaping is a lot harder. And I need to escape. If I cycle to a hundred-odd lighthouses, and write about them all, then I'll probably buy myself a year or two of good mental health. It doesn't even matter if anyone actually reads it.*

    -   Ireland is there. You can just go and see it, in your own good time

-   **tap into a massive marketing concern**

-   agents only care about money

**Book Pitch**

To the Lighthouse, Part 1:

Need

-   Agent

    -   write pitch & cover letter with Sean's help

    -   send to Faith O'Grady (RO'CK) & she can keep or pass on

    -   get list, if Faith no help,

        -   research appropriate people

Write

-   Cover letter

    -   Who I am

    -   What the book is about

    -   who will buy it

        -   other similar titles

        -   look at bestselling titles

    -   

-   Pitch

    -   Synopsis

    -   Hook

        -   men's mental health

        -   a self-help book with no advice

        -   cycling, manhood, language, self-help, me time

        -   reflections on mental health and how to cope

        -   **tap into a massive marketing concern**

        -   agents only care about money

-   submission guidelines

Send

-   50 pages, first three chapters

-   cherrypick as needed

-   

------------------------------------------------------------------------

## who I am

### **Busy busy**

I turned forty while writing this book and my

My life is as busy as the next parent's. Working, children.

Way too busy for any big adventures. When I began, in autumn 2022, my wife was pregnant with our second child and I wanted to get some momentum into a project before the baby was born and life became impossibly busy. Meanwhile I worked alone on a computer all day, wrangling data for cash, and we were furiously saving up to buy our own house. By the hopefully sea. Somewhere on the fringes of Dublin, not too far from my very elderly parents. Or a new life down the west, where our first child was born. Anywhere but the decrepit duplex we were renting in geography-free Blanchardstown where we had to transplant ourselves in late 2021.

### **In the beginning**

For the first year in Blanch, I took every chance I could to get to the sea. With the family or alone. If I had a gap to myself, I'd go cycling. Early on weekend mornings I'd scope out the towns of North County Dublin and get shocked by the house prices. Early one morning on a family holiday, I was aiming for Hook Head before guilt got the better of me and I went back to be with my wife and son. The next week I cycled to Poolbeg Lighthouse and my jottings became the first chapter of this book. Finally I had something to write about. I realised I had something to write about and had a format that would work within my lifestyle.

### **Writing**

I've always wanted to be a writer but I've just made too many excuses for myself. I have no imagination for fiction, not enough anger for journalism, and too much passion for the academic writings I have actually produced. Over the last decade, I have at least kept an intermittent diary, blasting out whatever complaints are fresh in my head, and from there I developed a habit of writing down the thoughts I have when I go cycling. I always have thoughts on the bike. New places trigger ideas and the slow movement provides space to develop them.

The book took on two new goals. Seeing the entire Irish coastline and finding a place to live.

s

-   Would we ever be free of the poverty tax of rent?

<!-- -->

-   Might we get to live somewhere nice. Surely I was too old now for

The sea makes me happy for no particular reason and I can't say that about many things

I craved space and freedom. The bicycle has always given me that but I need a purpose. A destination. A carrot on a stick, visible and aching to be reached. I can't just jump on my bike and cycle up and down a road for hours until I've broken a personal best and sweated my way into inner satisfaction. I need to see something. View the world. Or just find out what my own little island is like.

Explore the beauty of the Irish coast.

, with this project, I found it in cycling to lighthouses, whenever I had wee gap in my schedule. Bank Holidays. A cheeky Saturday. A family camping trip.

**Parents**

My parents took a very long time to get old and they slowed down the ageing process by cycling around the world in their fifties and sixties. To celebrate twenty-five years of marriage they cycled along the Danube and after that the trips kept getting longer until they cycled across Australia together, with Liz and Vinnie on the bike, and Tony the Triathlete in the back-up van. My dad's injuries slowed him down but my mam kept going, across America two years later and the length of Vietnam with Liz. Me and my big sisters would track their journeys on a map, and then listen to our their mad stories when they finally came home, bearing weightless postcards from strange lands. Their memories of these trips are stronger than anything they've ever done. My dad still bangs on about cycling up the Col du Tourmalet and my mam still feels the highs of cycling over The Rockies and the lows she felt on the dull plains on the other side.

I turned forty during the writing of this book and my second child was born. I had a bus

-   ~~dad with a job, turning 40, very boring~~

-   ~~in need for adventure, a bit of #metime~~

-   ~~pregnant wife. Knew i'd need to get something started before the baby was born. Once i had some momentum, it'd get done.~~

-   ~~parents were touring cyclists, inspiration~~

    -   ~~always came home with travel stories~~

        -   ~~dad still loves talking about going up the Col du Tourmalet, spoke about it on what turned out not to be his deathbed~~

    -   ~~mother always had travel books lying around.~~

    -   

-   Mental health issues, struggle for the right work,

-   Always wanted to be a writer

-   Adjacent interests

    -   spent a decade studying spelling cos I wanted to understand how it works in order to make up new words. Interest in word formation

    -   New Words in Ulyssess, Kre-8-iv Spell!nk in Band Names, Principles of English Spelling

    -   Accents. Spent 2020-2024 building the robot voices used by the Irish-accented Siri

-   

    -   

    -   

## Who I am and what the book is about

-   This book is about finding adventure in a life is too full for big adventures. I have young kids, a busy job, elderly parents, a good wife, and an intermittent urge to get away from them all. Cycling is a known cure for this urge, affording micro-holidays to beautiful places, alone or with friends. The sea. The mountains. Open spaces and new places. For me, cycling also provides writing material. Travelling fills my mind with fresh thoughts and washes away the nasty psychophlegm of my overfull life which often gets the better of me. I would write down my notes in a flurry and come home in a better mood, armed with the bones of a blogpost that I would never actually publish.

-   One day I realised that I could bottle this habit by cycling to lighthouses. The sea is too big and wobbly to provide a series of targets but a lighthouse provides the perfect carrot on a stick for me. A simple target to aim for. Without such goals, I feel empty, unmotivated and lazy. At first, I had no idea how many lighthouses there were in Ireland. The format didn't care. I could just pick one, cycle there, and over the following weeks I'd write about it, stealing an early morning hour before my kids and job needed me. I could then publish each journey as a blogpost and pull them all together at the end as a book. But I bottled it and never published the individual posts.

-   People would ask me where I was cycling from. At first, I was just cycling from my home in West Dublin, and the first section of this book is about the many on-land lighthouses along Dublin's beautiful coastline. But once I ventured beyond County Dublin, I realised that my real goal was to see the entirety of the Irish Coast, if I could. I drove to Balbriggan and cycled to Drogheda. Then I drove to Drogheda and cycled to Carlingford Lough. And so on. I also wanted to buy a house by the sea, and this project let me check out all the towns along the Leinster Coast.

-   A hundred-odd lighthouses encircle the island of Ireland, between active and disused ones, and I eventually realised that it would take me too long to cycle to them all, one by one, and then write about them with my ever-increasing verbosity. So I have broken the project into a series of books, with seventy-odd lighthouses remaining over three more books.

    1.  The mild non-Atlantic Way

    2.  The wild Atlantic Doris

    3.  Nair Nairn

    4.  Islands

-   There are twenty chapter-journeys in this book, covering thirty-odd lighthouses between East Cork and South County Down. That's five in Cork, four in Waterford, three in Wexford, four in Wicklow, eight in Dublin, three in Meath, one-and-a-half in Louth, and one-and-a-half in Down, with the split one straddling the border in Carlingford Lough. I forgot about the offshore one in Dundalk Bay but I did see the spot in Bray where there used to be a lighthouse, and the piddly new lights in the Greystones marina. I didn't cycle out to Rockabill Island or Kish Bank but I did cycle to the land closest to the lighthouses on islands off Dalkey and Ballycotton.

-   This book has two methods of storytelling. Words and pictures. The pictures mostly point at the beautiful places I saw along the way, including so many fabulous lighthouses. Years ago, when I was an illegal tour guide in The Vatican Museums, I learnt that the job was to point out the abundant beauty in front of the tourists. But when I brought them around the ruins of the Old Roman Forum, I had to build up a story from scratch, like tour guiding to the blind.

-   The writing is not about lighthouses but the task of cycling *to* them. It's about getting up, getting ready, learning to fix a bike, getting on the road and soaking up whatever comes my way. It's about dealing with my own day-to-day mental health issues and the complex trauma I probably underwent as a child in boarding school not much older than my own son. It's about the places I pass through, the people I meet, and my mixed opinions of the Irish way of life. It's about the coastline whenever I'm there.

------------------------------------------------------------------------

***How to adventure when you have no time***

-   Daytrips to every lighthouse in Ireland

    -   Hard to get it all done, so I tapped away at it over two years

        -   weekends, american bank holidays, Xmo, one sickie

    -   Mild non-atlantic way + The Burren + two in County Down

-   Self-help without the advice

    -   here's what I did to cope with being me

-   Immersive writing

-   Two forms of storytelling

    -   pictures for pointing

    -   words for immersion

    -   Rome Tour guide - vatican for pointing, forum for building up from scratch.

-   **Why**

    -   Something to write about that works for me

    -   Finding space for adventure within a busy life

        -   purpose, continuity of purpose

            -   format allows for this

        -   spontaneity

    -   Looking for a place to live

        -   town near the sea, good for kids, accessible to Dublin / home

        -   difficulty of buying a gaff

    -   Genesis

        -   book morphs from existing behaviour into a constrained and targeted version of itself

            -   I already used to get on the bike to get some P & Q

            -   “Sometimes ah think that people become junkies just because they subconsciously crave a wee bit ay silence.”

            -   Love of the sea

                -   I remember cycling out to Poolbeg maybe ten years ago, when I first got Blue Thunder and was starting to increase the radius of my life. I musta been hungover or miserable or both but I felt soothed by the trip and got into the habit of going places. Up the mountains was my usual refuge and then during covid when my son was three and my wife was working nightshifts in a Covid lab in Naas, I'd lob him on the back of the bike and we'd head to the sea. Something to do to pass the long days together. Poolbeg, The Bull Wall, Sandycove. Kids are welcome at the sea, unlike businesses, because they can act the maggot and stay safe at once. They'd be welcome in piazzas if we had any, but we don't hang out on the street any more, except in your maybe housing estate.

#### Length, scope, order

-   Project too big for one book

-   Dublin first then north then south-east/south

    -   Kind of doing it in a clockwise fashion

-   

## Who will buy it

-   similar titles

    -   McCarthy's Bar,

    -   Bill Bryson

    -   Dervla Murphy –\> took for more travel writers

    -   James Joyce, Irvine Welsh, RO'CK

    -   Tom Humphries (need to re-read).

-   Ireland Interest

-   Travel writing

-   Coffee table book

-   Anyone curious about feasible adventure

------------------------------------------------------------------------

Watching Ireland playing Norway in the 1994 World Cup

they'd collect postcards on the way.

-   parents were touring cyclists, inspiration

    -   always came home with travel stories

        -   dad still loves talking about going up the Col du Tourmalet, spoke about it on what turned out not to be his deathbed

    -   mother always had travel books lying around.

I mostly just write a diary and most of that is just me moaning about what's annoying me. But for some time I've bees

and I've too much passion to only write up my research on spelling.

I love the sea, I love the bike and I love cycling up mountains. I got this from my mother who began cycling when I was young

buy a house to get out of our decrepit duplex which the receivers were looking to sell.

------------------------------------------------------------------------

-   , the worlds I see, and the beauteous coastline of Ireland.

-   In the early chapters in particular, it is about dealing with my own mental health

-   It's about the landscape and the people I encounter and my beloved coastline. It's about the thoughts I have as I travel and the memories that are triggered. It's a form of therapy for myself, especially in the earlier chapters

-   The words reconstruct my journey and the pictures mostly point at the beautiful places I would see along the way. As the book progresses, I learnt to

-    filled with pictures of lighthouses but words mostly describe how I got there. I have left it to others to tell the story of this lighthouses as their passion is greater than mine.

-   The book is not about lighthouses. It's about going *to* the lighthouses.

-   spend weeks writing about it afterwards in the early mornings before the kids wake up.

-   And while I'm at it, I can see frighteningly beautiful places.

-   

-   Some people use speed or fitness as their goal but that's too boring for me. I need to go somewhere and check it out.

-   

-   Influences

    -   I worked brieftly as an illegal tour guide in Rome and the job taught me about two very different kinds of tours. In the morning, I'd bring tourists around the ruins of the Old Roman Forum and The Colosseum. This required me to build up

-   Lighthouses provide the perfect carrot on a stick, putting purpose on my aimless urges.

-   and the journey allows me to channel my urge

-   by having a series of targets.

-    I love the sea but it's too big and wobbly to provide a target. Lighthouses are the perfect carro

-   People would ask me where I was cycling from and, once I had cycled to all of the nearby lighthouses in Dublin, the de facto goal of the book was to see the entire Irish coast, one lighthouse at a time. Sometimes I

-   Cycling is a well-known solution to this problem as you can create mini-holidays of a weekend morning, free to roam alone or with friends for a few hours. I kept finding myself cycling to the sea, just to get out, just to go somewhere, just to get a

-   Gaps are rare when you have young children, a busy job and elderly parents, but the goal of

-   After a while, I just did it to do it. The project's inner momentum provides enough purpose and by the end I had forgotten why I was writing it. But when re-reading the early chapters, I could see its exlplicit purpose. Cycling is good for my mental health and it provides me with somethingn to write about, and writing is fun. I like to do it every morning between my waking up and my kids waking up. Not much more than an hour.

-   

-   the book continues on its own momentum, with its inner logic

-   

-   I'd just do it to do it
