---
title: "pitch"
---

my vision of hell is to go up and down the same road every day.

Explorer mode

starting to get bright outside and I can feel the bike calling me

I haven't decided where yet.

The lack of mountains on the Northside means that the sea calls even louder when I want at it,

Unfamiliar paths speed up the relaxation process.

The need for the sea

-   Here now is the relative nothingness where the unblocked sun bounces limegreen brightness off the seaweed slimefields and the retreating seawater lures my space-craving soul into a crazed chase for freedom. I follow the coastal bike lane and feel the seabreeze on my face and my mind empties of thought for a moment or three.

Taking photos has broken my momentum

I'm starting to take this lighthouse project more seriously and I'm thinking we're going to have to invest in a camper van or something if I want to make it happen. It's not like I'm going to be able to just nip off on my Tobler eighty or ninety times on overnighter trips to see lighthouses in Antrim, Donegal and Kerry. Our second bambino is on the way and getting out of Dodge takes planning now. This project will only work if we all go together and, while we're at it, we can check out houses to buy around the country. I want to live beside the sea even though it feels like an outrageous indulgence. But I understand now how my mam never recovered from moving inland from Clontarf to Lucan. The sea takes you out of your world and without it, escaping is a lot harder. And I need to escape. If I cycle to a hundred-odd lighthouses, and write about them all, then I'll probably buy myself a year or two of good mental health. It doesn't even matter if anyone actually reads it.

-   It is something I’m gonna need help for, although I’d still rather throw cycling, writing and meditation at the problem than prozac, as long as I can, although, to be fair, I’m not always arsed. 

-    Like, I can't sit and play with my son because I can't stop thinking how pointless it all is, but if I take him out for a walk then we'll have a blast and I'll feel better. If I stay at home, I need to do functional stuff like cleaning up or rearranging furniture. **If I go cycling, then it has to be somewhere because I need that purpose. A**nd I have to keep the locations changing or rotating, otherwise the pointlessness envelops me. I can't train per se. I couldn't sit on an exercise bike or lift weights in a gym or swim lengths of a pool. I just get depressed. I played so much sport growing up but I couldn't take it seriously after the age of sixteen and sport, along with nearly every profession, just seemed so emotionally lacking.

This is not a book about lighthouses. It's about getting to them. Getting ready, hitting the road and soaking up the world as I pass. But the lighthouse is the perfect carrot on a stick, dangling out there on my beloved sea. sa

They are just a carrot dangling

A place to go. A sense of purpose in the absence of purpose.

-   Since then I have had an activity in life with all of the joyous brutality of rugby except now I had the time and space to ponder life in real time. A place where my endless thoughts could find expression, coming and going in response to the changing landscape. A mobile meditation of sorts.
