---
title: "Mine Head & Youghal"
---

0354, Monday November 20, 2023

I'm off work for Thanksgiving week so it's a good chance to catch up on some lighthouses.

I actually thought it'd be next Thursday, but it turns out that Thanksgiving is on the fourth Thursday of November (the 23rd) not the last Thursday of November (the 30th), so it's a good thing I didn't book some winter sun in Morocco, like last year, when the chunfla was jumping waves in Taghazout. Instead, he's a in school and I've got a big of #metime. **Not sure it's worth including this**

I knew I'd wake up early cos my mind has been racing of late and I barely even bother wasting time trying to go back to sleep. I'm on the road by 450 and I've lobbed my mam's hoover into the MC Hammer cos I keep forgetting to drop it back to her, and their gaff is only a few minutes out of the way. I'm driving to Dungarvan, in the Munsterier end of Waterford, and I'm aiming to see Mine Head Lighthouse in the Waterford Gaeltacht, and Youghal Lighthouse in the People's Republic of Cork, the county I'm most excited about exploring. The cycle will be like 85k, when you factor in the whole coastline and I'm hoping to get it all done during the day's light. From 8am to 4pm.

On the motorway my mind is composing beautiful sentences, and I have them all written down in my head, but after I drop the hoover off, Google sends me across the back roads from the N4 to the N7, and now I'm burning good brain energy in negotiating narrow dark roads. I should have vetoed them and stalled it over the motorway, The whole drive is an exercise in wasting good energy and I hope this is the last time I go out and back in one day. You wanna be putting your best energy into the most important part of the journey, exploring new places, and not motorways. I also hate driving in the dark because I have a light sensitivity condition and I can't wear the midnight blue lenses I need to make the world look calm.

Today's forecast is fairly Sevu Reece and even though it's bucketing down here in Rest of Leinster, it is to be clear on the coast by sunrise, with intermittent sunshine throughout the morning, and nay rain shars araind.

0454, Monday November 20, 2023

Thanksgiving is this Thursday so I'm off work for the week. Now I actually though it'd be next week, cos I assumed Thanksgiving was on the last Thursday of November (the 30th), rather than the fourth Thursday (the 23rd), so I've no holidays booked. Plus we've just gone sale agreed on a gaff in Wicklow Town so there's not much cash floating around for Winter Sun, like last year's cheeky week in Taghazout, Morocco. So anyway, I"m driving to Dungarvan today, 200 clicks away, and then heading west, to - Tiredness

\- Dubstep wars

-   Stream the best of the lot

-   Or at least the one I was least tired for

-   Vexed is spacious and geometric and their music would probably look great on a visualization, but not tunes wise

\- Stop off after an hour

\- Get in behind a lorry and truck along at 95 clicks a paddy

\- Drop off hoover in Kew Park

-   Back roads

-   Too much brain power to be deriving those roads in the dark.

\*\*\*

There's no trains in this part of the country so I have to cycle back, which is always miserable

\*\*\*

Richard Fitz

\- The most soccer-mad kids in a boarding school where you had to fill your time with something.

\- Both of us were Blackburn fans and when one of us was sick we asked the other to come join in the infirmary, which was a thing. It was a refuge from the day-to-day life of school, the only place in the school where you could make toast or sit on your Gordon. Funnily enough, I was up there with nasty asthma, hooked up to a nebuliser, while the eponymous Gordon D'Arcy, in fifth year at the time, was visiting his mate and munching on toast eating toast. I had some kind of panic attack, and D'Arce had to rescue me, which was something I was incredibly proud of. Even in school, D'Arcy was a celebrity, and two years later, he was playing in the rugby World Cup. He actually went a wee bit off the rails for a few years after, just like all of us who spent their teenage years locked up in a boarding school, and the only difference being that he was missing Ireland caps while the rest of us weren't arsed showing up for club matches.

\- it's a reminder of how even with t

\-

\- . It's mad that he was famous even back then

\- Innovative, entrepreneurial in a way that I've since lost somehow

-   I'd organise lunchtime football tournaments and fantasy football

-   In Sixth Year, Fitz set up a soccer team for the fourth years and I tagged along for a bit as an assistant coach

-   Later he got into new media stuff. He had this blog called 52 Burrito Dates

-   

\*\*\*

I don't know if he honks at me or I just hear him or what, but I turn around and wave and cycle back up to him. He's as gentle as the collie at the door and I tell him that I was just with James.

Mine Head Lighthouse

James's daughter and Paid's granddaughter are in naoinra together

Accent is Sean Kelly's

I ask him to tell me a bit about the lighthouse and he starts out in proto-tour-guide mode with a spiel about it being built in 1851 and it being the highest lighthouse in the country, (wording) but I can now hold a conversation about a lighthouses so he chills a bit and we just talk for a while. He's not sure why the tower is so high, given that it's perched on top of a cliff, but there's nothing but fucking fog around here so maybe the height helps. The problem is that the records have all been lost as they were burnt in the London Blitz, wudyabelieve. He is sad that he doesn't know who owned the land back then, and I forget to ask him how long the land has been in his family. Like elsewhere, there seems to have been a bit of brouhaha over ownership of the land, although Paid is too mild-mannered to grouse openly. The lighthouse and grounds belong to the Commissioners of Irish Lights (CIL) but the road is his, and he put his foot down when they wanted to whip out the old Fresnel Lens. Their trump card is the presence of mercury, a substance that may have been the ruin of many's a lighthouse keeper. I didn't catch the exact resolution

The road down is as rough and sloppy as on any cattle farm and I probably should walk in case I get a puncture. But it's fun to do a bit of cyclo-cross even though I misjudge one corner and skid into a manure-filled puddle. Luckily I stay upright and plough on as far as the lighthouse campus. There is a red gate, in need of paint, with CIL welded into it, and a sizeable wall along the laneway to the lighthouse and around its grounds' perimeter. One of Páid's fields fills the space between the lane and the sheer cliffs below, so I rest the bike against the gate and plod across its sog. The wall is lower in one spot so I scale it there and stroll down to the tall.

I'm always amazed at how sturdy lighthouses can be, as shockingly gargantuan in stature as a forward in international rugby. This one is painted black and white like a Barbarian, and set beside it are two cottages, and more thick walls separating them and marking out two plots which were surely used for growing vegetables.

-   Something about the bit where the light is (blocked off, boarded up)

-   Some nice sunlight

-   Can't capture the drop to the sea, but the photo of other cliffs might do

T

nd thankfully there's an electric barb wire fence demarking the field and preventing me from going dangerously close to the edge. \*\*\* Punch on. - Not a lot done, much more to do. It's 29k to Youghal and 32 if I go via Ardmore, so I decide to check it out for completion, and Richard suggested it.

-   It's as mild a day as you'll get in November, twelve or thirteen degrees, with the sun breaking out from the clouds, yet the wind remains fierce and you can see its impact on the echelon-shaped trees which grow in response to the prevailing wind. All day I'm putting on and off my magic gloves.

-   I barely meet a car and I get lost in thought so I must have been in the zone. One day these serene roads will be filled with leisure cyclists and, in preparation for their coming, they have already been marked out as part of the Euro Velo project, which has the decency to include Wexford, Waterford and East Cork, unlike the Wild Atlantic Way. For now, the tourists remain glued to the West Coast, yet everyone has to compete for space along the few roads that got built along its craggy terrain. Here, where the land is good enough for cattle farming, and oodles of road connect it all up, cycling is perfect, because cars and lorries can zoom along the main road (N25), while no one comes to this appendix peninsula.

-   

-   must compete for space along the few roads

-   

-   This part of the country has the same misfortune as the second- or third-prettiest sister in a family of stunners.

-   

-   of being like the second or third best-looking

\- https://en.eurovelo.com/ev1?gad_source=1&gclid=CjwKCAiAx_GqBhBQEiwAlDNAZglc1iUDslyfMM_zcWtNQniHJJqexVBpuPukR1HnO_xEtlZniXzUdRoCPe8QAvD_BwE

He introduces himself as Paid Morrissey

\*\*\*

The next two journeys both involve people I know

\*\*\*

I've an old mate from round here called Richard Fitzgerald and I last caught up with him at our twenty-year school reunion last summer. He flew home from Dubai on the Friday, did a half iron man in Youghal on the Saturday morning, and then stalled it up to meet us in Blessington that evening. On the Sunday morning, we loaded his bike in my car and I dropped him off in the airport whence he flew back to Dubai to continue running his media empire. Although in fairness he was running it from his Tony all morning. It was a great chance to chat to an old friend who has built up something and to see how he does it.

He was reading about CEOs and football men when we were fourteen, fifteen.

I never had any interest in business but he managed to see the link and make the transition and even a cursory check online shows him talking about applying football or tennis pressure to your business life.

So I texted Fitz last night to see if he had any suggestions and he sent my his brother James's number. As it happens, he's just opened up a triathlon shop in Youghal and I thought I might catch him there or for coffee but he's off on a Monday and so we work out a plan here in Waterford. I send him my live location and, once the kids are in school, he just pursues me in his Jammer and catches me at Helvick Head, at the southern extremity of Dungarvan Bay.

We go for coffee in Sólás na Mara, a wellness centre beside the harbour, so clean that I decide to take my cycling shoes off.

where his physio works and the

you can have massage or seaweed bath. Everyone knows James here and it's nice to see the dynamic. This is something I want for my family. The view over Dungarvan is spectacular but it's cloudy, misty and nearly dark, so I don't bother taking a photo. It reminds me of a smaller Dublin, with a circular bay and a low-lying town where the river meets at the centre. On the far side of the town is a ring of hills and it's obviously elevated here on the Youghal side as I can see over the town, having dragged my knackered body up the long drag. It doesn't take much imagination fill in a bigger town, unlike poor Youghal which is like barnacles stuck to a hill.

I parked on the other side of the town because I wanted to get a sense of the place James is appalled at the hack of me although he's too polite to say anything until we're a good bit into the conversation. He wants to know what's in my bag, the one I'm lugging around on my back. I start explaining myself and he correctly points out that I'm going to have an answer for everything, but really it boils down to why I'm cycling. Our purposes are different. Last week he went out for a hundy k and all he had was like a bottle and a bar. I tell him I"m out for a day's work. I need my phone to take photos for my book. I need a change of clothes so I can swim in God's ocean. But I do need to keep editing my load. I will need my car key at the end of the day, but I don't need the other hundy grams of house keys and key rings. I also need proper warm gear, designed for cyclists.

ADD photo of Tri Hub

-   Knows everyone

-   This is something I would like in life

-   Needs to talk to the physio cos his knee has been banjoed since he did the Dublin City marathon, and he points to his hat from the occasion

-   There's talk of Amsterdam and its flatter course

-   He was on course for the family record until his IT band seized up after 28k and

-   There must be fierce competition betwong them all

-   A fierce urge to succeed.

-   Thirteen years ago I was helping Richard tidy up the blog he was writing. Spelling and grammar and other fun stuff.

-   
