---
title: "Howth"
editor: visual
---

*I planned to cycle here on in October, the week after I went to North Bull lighthouse and formulated the project in my head, but my son woke up as I was getting ready and I soon realised that he wasn't going back to sleep. So I decided to turn the L into a W and we drove out to Howth together and watched the sun rise as we walked down from the summit car park, and around a wee bit of the outrageously beautiful bayside walk, before his five-year-old legs started to get tired and we tramped back up to the car. I took a wodge of photos that day and I'm using them here because the light was extraordinary and I ended up being in a rush. So if you are sitting here wondering about the position of the sun at particular times of the year --- which I increasingly am myself --- then that's why the Baily Lighthouse in Howth is looking like it does.*

1048 Saturday Jan 7, 2023 I hadn't planned to go cycling today, but I got some bad news yesterday and it split my soul in two and I can feel a bout of depression being triggered, in a way that I've never been so explicitly aware of, and I know I need to take action. I don't get depressed in the sit-in-bed-all-day kind of way but I do feel an emptiness in me whereby basic life seems so aimless. Like, I can't sit and play with my son because I can't stop thinking how pointless it all is, and so I'll usually take him out for a walk and we'll have a blast. I need to do practical stuff like rearranging furniture or going cycling somewhere. And not just going cycling. It has to be somewhere because I need that purpose. And I have to keep the locations changing or rotating, otherwise the pointlessness envelops me. I can't train per se. I couldn't sit on an exercise bike or lift weights in a gym or swim lengths of a pool. I just get depressed. I played so much sport growing up but I couldn't take it seriously after the age of sixteen and sport, along with nearly every profession, just seemed so emotionally lacking, and I could never again commit myself to the rugby and cricket I had been playing insatiably. All that training seemed like such a loadamebollocks. I decided I wanted to be a writer, like George Orwell, and write about how shite everything was, and I knew, from Samuel Beckett, that my career could last until my eighties, unlike with sport. In my twenties I poured booze into the hole in my soul, and I played five-a-side football with the lads, and a smattering of junior rugby, but fulfillment only came when I discovered cycling. I was doing rehab from a knee operation and I had to bulk up my little skinny leg and just wasn't doing the gymwork. My physio Andy Watson told me cycle up hills, preferably in a higher gear, and one day I battled my way up the Wicklow mountains on my shitty-ass city hybrid bike, and since then I have had an activity in life with all of the brutality and joyous pain of rugby except now I had the time and space to ponder it all. A place where my endless thoughts could find expression, coming and going in response to the changing landscape. A mobile meditation.

So anyway, I'm in the kitchen, cleaning up after breakfast, and I can feel the emptiness. We've no plan for the day and I can feel the nothingness come at me. But I know too that the issues from yesterday are triggering the trauma of going to boarding school when I was eight years old, so I get the idea of putting on some songs from that era, because there are so few details that I can remember properly, but the songs remain the same. First I stick on Glory Box by Portishead, released in 1994, but my memories are actually from my secondary school days, and then I lash on It's my life by Dr Alban, which was a big hit in 1992, and immediately I'm in tears. I'm only nine and I'm back home in my folks' gaff, and it's time to go back to school, cos it's Sunday evening. Atlantic 252 have announced they are going to play it any minute and I"m waiting and waiting cos I want to tape it and then I'll be able to listen to it all week on my walkman. But we have to go and I don't get to tape it.

The cure 
I go up for a shower and afterwards I declare I need to go for a cycle to help me process stuff. My wife and son are up for going to the playzone area nearby so I drop them there and head out towards Howth. The cleanest and nicest way there is to take the canal into basically town and then jump on the cycle lane all the way up the coast from Fairview but I'm in the humour for piecing together more of the Northside, so I take the Abbotstown quadrant around towards Finglas and then hop onto that ringroad that pieces together the inner outer Northside all the way to what turns out to be Killester. It starts out life as Glasnevin Avenue and then it's Collins Avenue, but it's basically the North Circular Road, part deux. It's wall-to-wall traffic lights and junctions and I wouldn't recommend it unless cartography is your goal. Everywhere in the inner outer Northside seems to be a road, not a place, kinda like Belfast, and you never feel you are in a village. Every so often a church emerges, the size of a football pitch, but they mostly look like placeholder prefabs, made of cardboard, and erected to give mass to the newly housed locals, before the real church gets built. Even the names are too Catholic. We're talking Holy Child Roman Catholic Church, Whitehall. We're talking, Our lady of consolation, Malahide Road

It can be hard on the Northside to distinguish between road and place, and no effort was made to separate gaffs from thoroughfares, as they are on West Dublin, which was developed in the last thirty years. The upside is that you are just cycling through suddenly there's a church the size of a football stadium

The biggest landmarks are the massive churches that were plonked there during the housing expansions in the post-way era. The one in Whitehall looks like a cardboard placeholder, used to give mass to the new residents while the real church is being built.

at the peak intersection of Catholicism and housebuilding back in the sixties and seventines, and the church in Whitehall looks like a cardboard version of

https://commons.wikimedia.org/wiki/File:RC_Church_of_the_Holy_Child,\_Whitehall,\_Dublin,*Ireland*-*geograph.org.uk*-\_332078.jpg

I drop my wife and son to the playzone area nearby which they love going to

and although the memories are actually of a Sunday afternoon at home home when I'm like fourteen, which is a few years after it was released, and then I stick on Immediately,

--- there's only so much commitment I can make in advance when I need to be able to resolve my emotional problems in rea l time ---

It was due to come on Atlantic 252 any minute, and I was going to tape it, because it was Sunday evening and it was time to go back to school, cos that's how it was.

response to the changing landscape, and the thoughts can come and go. A kind of meditation basically. One that I can do for the rest of my life, unlike

which brings deep warmth and satisfaction to my soul, like nothing else except for writing.

it all felt so emotionally lacking to me so when I discovered cycling, at the age of nearly thirty, while recovering from an ACL injury, I found an activity with all of the brutality and joyous pain of rugby but with the time and space to ponder it all. Somewhere where my endless thoughts could find expression, in response to the changing landscape, and the thoughts can come and go. A kind of meditation basically. One that I can do for the rest of my life, unlike

the pain, in a way that

and to meditate on what the body needs to do to

I can't sit and play with my son because. 
Now I could probably sit there and play with five or ten kids cos there is enough engagement to fill me,

I always feel this worst on a Saturday because work occupies me during the week, and I crave people to fill the void. When I was younger I just poured alcohol into the problem and filled my time with squillions of drinking buddies, and while some them are my best friends, I have drifted away from many more.

some of whom are my best friends, and many of whom I am less connected to nowadays. When I stopped drinking professionally, in the sense that it was my main occupation throughout my twenties, my human cash flow fell off a cliff and it was hard to find t

and I need people around and to have fun, but

## need to get out there and process some of it and generate some
