---
title: "Blackrock Castle"
---

I got in to Cork City at like half ten last night, parked up outside St Patrick's Church, and then kipped in a dorm room in Sheila's Hostel. As soon as I got to the hostel I was to text my wife – which I did, tobefairtome – to confirm that the place wasn't a basically homeless shelter, cos you wouldn't know these days. I was half embarrassed to be in a hostel at my age but I remember from my galavanting pisshead youth that there were always a few oddball cyclists kipping in hostels, sober and old, in need of a cheap mattress and an early exit. I'm actually surprised to see how many people my age or older are floating about, between muinteoir types leading teenage groups, and just a few prettymuch weirdos.Nothing else has changed in the eleven years since I was last in one of these places. Giddy reception staff. Tiny unisex bathrooms. People planning out their trips of an evening. A twat with a guitar. Luckily there's no bar. In my room, everyone's asleep at half eleven when I climb up the creaking ladder into my top bunk. The bed has a ledge welded onto it with a USB port and I reflectwith delight that is the only notable difference since the last time I was in one of these places, back in 2013. Wouldn't it be so soothing if we could maintain this glacial level of technological progress over the remaining few decades of my life and focus on the human side of life. I wake up at half three having a nightmare about being squashed among dozens of people in a maybe gas chamber. The room is windowless and thus airless. I get out of the Margaret, hit the Soviet, and notice that another room's door is being wedged open with a bin. I do the same for my room and kip away til half six when the loudest person in the world wakes me up, rolling a needlessly cigarette in the dark, on his bed, like a prisoner.

I'm heading out to see a mingin spidery lighthouse in Cobh today and either before or after, I'll go for a tour of Blackrock Castle which used to be a lighthouse and is now an observatory. I still don't know my route but my goal is to understand the watery complexity of Cork City and environs. The city centre is an island on a river which explodes out into an enormous inland body of water, with islands and headlands and ports and boats. I got a sense of the other side of the harbour, a simple contiguous landmass, on my way to Roches Point Lighthouse. But here on the west side of the harbour, a lot more is going on, between the City of Cork, the Port of Cork, and the Cove of Cork, transliterated into Irish, post-independence, as *Cobh*. Then you've got Ringaskiddy and Crosshaven on therr own little peninsulas in the south-west of the harbour, although I don't know if I'll get to them today.

It was lovely last night to do a visual recap of so many places I've been to in the last year along the southern coast, with the sun setting slowly in front of me along the N25 and a crescent moon popping up to play beside it.

-   Each day out is so recollectable, between the memories of being there and then the long, slow, grinding mastication of that memory into readable words.

-   But seeing it allows the memories to fit back into the geography.

-   It feels right to finish up this book in Cork, Dublin's wetter, mellower little sibling city.

I get the flock out of there and I'm drinking coffee in Bus Stop Coffee by 7am, where the owner is telling me all about the Pakistani fella who won the javelin there last night. We reminisce about watching the Barcelona Olympics as kids, him with tonsillitis and a black-and-white telly in his bedroom, and we swap Covid stories, with him being delighted just to get a rest from aeons of coffee making, and me hanging out in Lake Tahoe in a half-price Airbnb atop a mountain. It's quality chat for this hour of the morning but I have work to do. I need to ditch the jammer, preferably for free. Your man can't think of a handy spot with free all-day parking but I ask a streetcleaner for suggestions and he racks his brains for a bit - you can actually see his head wobble as he thinks about it - and then suggests I head for Ballyvolane Shopping Centre, up the hill. There are a couple of council estates along the way where I'd be safe enough he reckons but I decide that outside Dunnes is the easiest, cos I once parked for the day outside someone's gaff in Ballyfermot once and they double parked on top of me to learn me a lesson, and it was great fun knocking on the door to ask them to mover their car for me. So I drive up the steep hill out of town, knowing I'll regret it later when I'm knackered, but I'm delighted to be able to look out towards the whole of the city, if you discount the trees and buildings obscuring the view. I spot a street called Bellview Crescent and follow my nose, then a local's directions, to a viewing point down the back of a grassy lane (*Bellevue* *Park*), where you can stand on someone's wall and look out over the whole city, but it's impossible to get a snap of its width, or appreciate the complexity of the interlocking waters. I know that the city centre is on an island with the river splitting around it, but you can't see that from here. All that stands out are sundry large buildings, mostly along the river, and a large expanse of low-rise buildings, with a chain of shallow hills in the background. I ask a postman where I can find a better view and, a little shocked by my disappointment, he recruits a local who suggests the Montenotte Hotel. It's a fancy modern hotel, the kind of place I imagine Paul Theroux, resting up after an evening of "romantic voyeurism"**,** drinking cocktails, getting a massage and maybe even a happy ending. But the views are blocked up by fluffy trees. All the same, I do love the way you can just snoop about a hotel's grounds for entertainment, and if push comes to shove, you can just order a coffee or a pint and hang out. One or two euro extra for a dose of mild opulence. Further up the steep river bank, the older Montenotte House has better view of where the river spreads out into the large Lough Mahon to the East which is shiny blue in the morning sun.

I'm starting to get a sense of what is going on and I finally have my route planned out. I'll follow the river to loop around the city centre. I remember it going to UCC and the cricket club, both of which I want to see, and then I can loop back into or around the city and out the docks towards Blackrock Castle. From there I'll head for Passage West to catch the ferry to Cobh and afterwards I'll either do a tour of that island and back via possibly Fota Island, or else I'll head out to Ringaskiddy and Crosshaven if the urge takes me.

around the city centre along the river, down towards UCC and the cricket club, for a bit of nostalgia. Then I'll follow the widening river out to Blackrock Castle, where it opens out into Lough Mahon, and then make my way for

so I descend back down to the town and see the streetsweeper now out yapping to the barista. The two lads being the public face of the city.

Wikipedia summarises the geography better than I can:

*The city centre is an island between two channels of the [River Lee](https://en.wikipedia.org/wiki/River_Lee_(Ireland) "River Lee (Ireland)") which meet downstream at its eastern end, where the [quays](https://en.wikipedia.org/wiki/Quay "Quay") and [docks](https://en.wikipedia.org/wiki/Dock_(maritime) "Dock (maritime)") along the river lead outwards towards [Lough Mahon](https://en.wikipedia.org/wiki/Lough_Mahon "Lough Mahon") and [Cork Harbour](https://en.wikipedia.org/wiki/Cork_Harbour "Cork Harbour"), one of the largest natural harbours in the world."*

I've been here a handful of times in my life, cricketing as a teenager, drinking in my twenties, and a couple of later trips to get my eyes and brain tested for light sensitivity, but I always seem to be crossing bridges

#so I've decided to try and understand its la

------------------------------------------------------------------------

Work

-   It's odd to look at people going to work and I'm thinking, I *never* want to do that again, even in a unimehversity?

Mardyke

-   So I stall it out to the Mardyke to get the shape of the city adnd a trip down memory lane

-   explanation of place, Dutch dude, see photo

UCC

-   beautifully manicured campus, buildings well hidden behind the trees and sequoias, reminds me of Scoil Oilibheir, instead of the functional squish of Valentine's new school.

-   Shandon Bells house, Irlen glasses,

-   loop around campus and back to the city

City

-   warm day, could be central europe, croatians sitting out having their coffee, sun shining

-   People scrambling to buy shoes, no interest in hanging round

-   

Docks –\> Blackrock

-   Port of Cork

-   Marina Market, hundy pee coming here later for my dinner

-   Set up during covid and developed from there, bizarre setting, refused permission

-   a chunk of city which is being repurposed. Large derelict buildings and emergent facilities e.g. Marina Market

-   Rip it up and start again space. Always good to get some breathing space in this country cos verything is so old and cramped

-   spacious, semi-developed park which houses Pairc Ui Chaoimh

    -   astonishing that Munster Rugby plays Limerick when they could be here with a larger population and much better attendances

-   A Turkey-shaped appendix peninsula with limited access

**Blackrock Castle**

-   Restuarant, please wait to be seated

-   my back is up,

-   No cycling shoes inside. Been outside all morning, would rather be inside to warm up a bit

-   has to ask the general manager as though she herself is already some kind of manager

-   shite music, David Kitt UCD arts block, The Slate

-   scone, whipped cream and a flower which I eat in case it is nice, which it isn't, but it reminds me of my dad's garden, possibly eating flowers as a nipper

-   Tour Guide

    -   prattling through her spiel, passionless, but the spiel was corroborated by a video which nicely presented the work of ohe in-house astronomer.

    -   whistestop summary of the building's uses over the century, getting burnt down, being used as a restaurant and so one, rowing club etcs

    -   but when it fell into disuse in the early 2000s CHECK, an appeal was made to the public looking for suggestions as to what to do with it. Some astronomers from

        -   <https://www.irishexaminer.com/lifestyle/arid-20388034.html>

    -   no one seems to know about the castle being a lighthouse til 1903 and it is just mentioned in a lighthouse directory REFER

        -   <https://www.ibiblio.org/lighthouse/irlsw.htm>

        -   <https://irishlighthouses.blogspot.com/2014/05/blackrock-castle-cork.html>

-   Cork flag in

-   Phone is charging so I can't get a photo.

Passage West

-   Semi-formal greenway

-   lovely river slash lough views but windy AF

-   loops around to Passage (West), punctuated by some bits on a wide path, but they are getting there. Great to see

------------------------------------------------------------------------

-   Smashing Pumpkins on arrival

-   Build up to #3 via the surprisingly hard drumming on Tonite Tonite

-   Zeri seemed mellow and Here is no why perfect

-   

------------------------------------------------------------------------

, then chiselling it all down in word formation,

a**lthough the best story I came across was the two Afghan sisters who fled their country after the Yanks bounced, and made their way into cycling road race, with one of them in the ob**

then wedge the door open with a bin to let some air in. I'm awake at half six

------------------------------------------------------------------------

Cork City is a complex place and I've never understood it very well, with all its bridges and looparooneys and impossibly steep streets on one side, so I've decided to follow the water and try to understand its topography that way. I'm parked on the smaller North side of the city, not far from the train station

<https://en.wikipedia.org/wiki/Cork_(city)>

**CAFE CHAT**
