---
title: "Dun Laoghaire 2: South Dublin rural loop"
---

0950 December 29, 2023. A Friday apparently.

It's six degrees and windy in Dublin today, but no rain is expected, although I forget to check the Dublin mountains which I'll be quotunquote scaling later on. I'm heading to other Dun Laoghaire pier, with the green lighthouse, and because I like to make things difficult for myself, I've decided to map out the South Dublin Rural route which I've been piecing together for years and reckon I can finally nail today, doing an anti-clockwise semi-circle around the unspoilt outskirts of the suburbs. You start out on the River Liffey, in town or wherever, and follow it\
upstream to Chapelizod and Lucan village, along its admittedly North Bank, then you rise slowly through Backweston, Hazelhatch, Newcastle and Sagart, before taking on the Dublin Mountains, stopping off for grub in Johnnie Fox's, Ireland's highest boozer, and then whizz downhill to the coast to cool off in the sea if the descent hasn't already sucked the heat out of your body. Your endpoint could be anywhere in the built-up coastal suburbs of Dun Laoghaire, Dalkey, Killiney, although there is probably a rural(ish) path to Shankill, an area I don't know well yet. The only rule is that you have to stay in County Dublin throughout, a county whose underappreciated beauty is a hill I'm willing to die on, although in planning out the trip (for once), I was unable to dodge a few hundred metres of spillover into County Kildare because the growth of Adamstown has necessitated it.

In my case, the endpoint will be Dun Laoghaire East Pier, a lighthouse which I have been saving up until I have the right moment. And that's today. It's the Perineum Week, the gap between Xmo and New Years, and I'm ready to get out of the Roisin while the family are still happy to chillax at home. I'm not ready early cos I like to look after the bambino in the morning while my sleep-deprived wife catches up on kip, so it's nearly 10 o'clock agin I'm on the Dermot. I had only planned to go on a smallish spin with Arthur but he ended up on the lash with his new bird, so it's just me, myself and the Falcon. I lash on a body warmer, a cycling jersey, a windbreaker and one of about seven orange bibs I've been guiltily hanging on to ever since I quit Cabra football. Downstairs, I've got long johns on with cycling shorts over them, the wrong socks and my cleated cycling shoes. One day I'll sort it all out. I pack minimally, with just a spare jersey in my back pocket and a wifebeater snood, to double up as an undergarment on the train home. For sustenance, I grab an apple, an avomikado, three small nartenges, some salted peanuts and some qualobant Spin 103.8s I got for my delighted wife in the Halal shop last night. She lobs some vitamins into my water bottle and gives me a fibre sachet too along with a coke-bag of spirulina. The bike has a slow-release puncture, but I reckon I'll be grand cos I pumped it up before bed and it barely flattened overnight, so I give it a quick blast and say my prayers. I need to buy a new frame pump, but. The wind should be on my mostly back, as it's coming from the south-west, as per, and I'm cycling mostly eastward, bar the first chunk.

I need to get to the Liffey first so that involves Manhattaning through Dublin 15, from my gaff to the Strawberry Beds, just as I did in the first paragraph of this book. Since then, I've learnt that its lack of soul is caused in part by the distributor roads which save you from ever passing a property, as these are all walled away and disconnected from the outside world. As you sit in the miserable traffic, the only people you see, ghosting along the pavements, are the carless poor or youths, hungry for interaction and generating it out of thin air or vapes. Weaving across this matrix are the more adventurous walkers, often armed with a dog, a tiny number of cyclists, and a growing fleet of e-scooterists, squeezing through what few pedestrian gates they've been granted, as these walled demesnes are designed to keep out strangers rather than make life liveable for residents. Frequently, pedestrians will scale walls to save themselves a nonsense looparooney and close inspection often reveals bits of waste furniture placed strategically to provide a leg up. The design derives from rural Ireland, except now the inaccessible fields are semi-inaccessible housing estates and apartment complexes. It's not long since this was all just fields and my dad would come here to assess weeds among the crops and advise farmers on how to #spray them. An unlikely survivor from this era are the blackcurrent bushes in his garden - and now my sister's too - because in like the '70s, a fella told him to come over and grab whatever plants he wanted from Coolmine Estate, before it was turned into two schools and a leisure centre. Other survivors include some grave yew trees and giant sequoias outside Scoil Oilibhéir and the adjacent Millenium Park, while some dead tree trunks have been beautifully carved into huge wooden sculptures, as part of Fingal's stealthy efforts to improve their virgin parks.

Yet getting from Blanch to Lucan on a bicycle is a joy because the two West Dublin suburbs are separated by the narrow Liffey Valley which provides a tunnel of riverside reprieve between their respective faceless sprawls. I turn down the newly-paved Rugged Lane, where eking past other cars is now purely a matter of driving dexterity and good manners, but no longer a potholed-infused hazard for your vehicle. Unlike in the Poolbeg chapter, I turn right along the Strawberry Beds for Lucan village this time, and before long I pass the Shackletons' defunct mill. Seeing my home territory afresh, I think of Ernest Shackleton himself and his descendants who were a few years behind me in primary school. I must also text Marco cos we've agreed to start compiling a list of adventure stories. It's not long since I listened to *Endurance,* [Alfred Lansing's amazebant book](https://www.goodreads.com/book/show/139069.Endurance) about him leading his crew out of their Antarctic and next week *Empire* podcast are doing [a two-parter about it](https://twitter.com/tweeter_anita/status/1743928625190088797)**.**

I stop at the bridge into Lucan to look at the weir and the river is nearly bursting its banks, and there's an old-timer there doing the basically same. He tells me it burst a while back and nearly got up to the apartments, and then we reminisce on the floods of June 1993 when the Griffeen tributary round the corner flooded Kenney's pub while he was in having a restorative morning pint. In fairness to him, I remember it being a Saturday, cos its was Half-Term in boarding school and Sports Day was cancelled. That evening was one of the happiest memories of my childhood as me and my dad went for a walk together, a rarity back then, to scope out the other flood point, below the Spa Hotel. We took a disposable camera, which was something you only did when you want on like holidays, and I remember being devvo when the snaps didn't come out.

So your man reminds me that the council are after buying the Italian Embo and he reckons they'll have space enough to lash in a car park which would do wonders for the village, which I reckon could become the nicest village in inland Dublin. I start banging on about #greenways and he even suggests putting a cycle path all the way in to to town. I'm delighted to see the idea is in the local ether. My brother-in-law also suggested that Shackleton's mill be turned into a tourist attraction in its own right - maybe lash in a wodge of Antarctic memorabilia while they're #atit. We still haven't fully grasped low-key river tourism in Ireland, beyond the Jack Charlton fishing approach, and I'd love to do a tour of France cos Dexter, ithinkitwas, says the place is awash with river amenities these days. Fake beaches and the likes. Blake-Knox might know more cos he's a wil' man for some river swimming, where the water cleanses your skin and the parasites clean out your probably insides.

I buzz through the village and grab some jam from a one-off street vendor who does be outside the Protestant Church, flogging twenty-plus varieties. I get some experimental marmalade cos there's never any shortage of berry jam in my folks' and decide to nip in to my aulfla for a quick hello. I turn right at Courtney's and up Primrose Hill and then think about turning left by his old shop on this side of Tandy's Lane, but as I see the petrol station which we still call the *BP*, I can hear Yo la Tengo in my head singing *My little corner of the world*, with the bus stop into town and the entrance to the Lucan Demesne, where we came to see those floods thirty years ago. The demesne is a magic spot, with a linear park along the river, and it keeps my parents and many others sane amidst this sprawl. It feels like this converging depression will morph back into a tiny village. Back in the David Norris, town people used to stall it out here on the boola tram for the spa water, hence the Spa Hotel on high above. There was a path down, but I don't remember it, just the roadworks as the dual-carriageway was being put in, and I was amazed to see in an old photo that there used to be some shops here when my big sisters were young.

I swing on up to my folks via the dualler and I haven't brought my 300g of needlessly keys so I have to knock on the sitting-room window where Big Val is having his mid-morning doze. He jolts in his medical chair and then hobbles to the door with his stick and lets me in. He says my mother has gone out for a break and he laughs and he's delighted I've brought him marmalade. He has a fierce sweet tooth and my mam is stickler for simple food so you nearly need to smuggle it in. I tell him I don't have time to stay and I legiterally don't yet it's curiously offensive to not have a quick cup of tea. Even to me. I don't like rushing in his presence, partly because he won't be around for long, but really because his nature is so calming. He has never lived in the past or the future. He's just right there, in the moment, like a cat who cracks jokes all day. Looking after him is not a chore but constant laughter, as long as you don't try to give him a shower.

because his memory for names is poor. I

I explain to him today's route around South County Dublin, all places he would have cycled around for about twenty adult years, but he's struggling to piece it together and his memory for names is poor now. If it was North County Dublin, where he spent twenty childhood years, it'd be burnt into his brain. He laughs when I mention that Slade Valley is on top of a hill.

He can't remember the name of the carer who was just in doing his exercises with him, though it was the good one, who goes the extra mile, not like the ones who just do what they have to. But he remembers she's from up near Tesco (Dodsboro, unnamed) where the fella (unnamed) is from who my eldest sister (name remembered) married (actually they were just engaged...). This narrows it down to two carers so I ask if she was a young wan. Of course that's a shite question cos when you are nearly 89, everyone is a young wan. So I ask if she was 25 or 45 and, bursting into laughter, he says 35. I hit the Dermot and leave him back to the empty day ahead, although he'll be glad of it today after six family events in the last five days. As I'm leaving, he asks for my wife, whom he loves dearly, but he can't think of her strange name either.

I climb up the ramp to get off the N4 and turn left for Celbridge. I've long since learnt to avoid this road, so I turn left back towards Lucan Golf course and right up Tubber Lane, which is now a cul de sac for cars, ever since the Shackleton development in Adamstown slash Dodsboro pushed back the suburban boundary. Despite the new estates behind the hedge, I'm out of the city at last and it feels good. These are the roads I used to cycle to my dad's shop in Newcastle for all the summers I worked there before the recession put an end to it. I know I've entered Co Kildare when I see a signpost for Arthur's Way, a route celebrating good old Arthur Guinness, who first brewed the black stuff in what is now Boyder's gaff in Leixlip village, with its Dexter Gordon backing onto the Liffey. On the t-junction in front of me is a house where a dog used to lie in waiting and then chase me every morning, and I'm still afraid that one day a dog will catch me on the bike. The road becomes the county boundary for a bit, and the left hand side must be Dublin. I pass Hazelhatch train station and turn left for the canal bridge where McEvoys thatched pub has carved out a beautiful niche for itself, beside the barge residents, whose number has grown significantly since those glorious Celtic Tiger days.

It's a couple of clicks up the Hazelhatch road before turning left to Newcastle village, where the old thatched pub lies in burnt out ruins, but the rest of the village has finally been populated with houses and shops, giving it the contiguity it never had. This village is not on the road to or from anywhere so people need a reason to come here, and there were precious few. For twenty years, our shop brought in all sorts and was the biggest melting pot of Irish people I've ever seen. There was a dwindling collection of local farmers getting feed for their cattle, sheep, hens and horses, and lots of horsey people came from North Kildare or the Dublin mountains where I'm going next. Another breed of horse owner came from the estates in Clondalkin and Tallaght, most of them second and third-generation city people. Then there were regular travellers living in uncharted places with no signposts. I remember being blown away as a teenager that there were Irish people whose accent I could not understand. Several of these groups converged for races held on like the Naas Road of a Sunday morning. Others converged for dog fights and I remember a handful of regulars being sent down for it. But anyone can have a dog, so that also brought in surburbanites from Lucan and Celbridge, and they might grab and they'd often be shocked at the actual hack of the place. The banter quotient was something else and we had a nice comfy chair nestled among stacks of animal feed. Some customers would just sit there and soak up the craic or looks for tips for the races. The Celtic Tiger put cash in the pockets of everyone, and that added an intensity to the manual work which hadn't been there in the 90s. I remember coming up here with Babs when I was really young and the place was dead. Dick Smith would sit on the wall outside, watching nothing go by, and Trisha Smith, no relation, would come down from the hairdressers upstairs and drink tea with Babs. She was still lifting bags when she was seven months pregnant and later her husband took over, and later again my dad joined up when the original branch in Lucan had to close. I'd work long slow summers and intense Saturdays throughout the year. The whole operation went tits up in the recession and there was talk of someone washing money nearby, and I'll never forget the misery of being out of stock and losing customers every day, around '08 and '09 when the shit hit the fan. It was tough going on my dad and especially my brother-in-law who tried to keep the show on the literally road before packing it in. We were fifteen years behind the curve on mechanisation because there's only so many bags of feed one person can handball per day per year per life. But by Christ was it good craic dealing with all those people coming and going, especially for a little sheltered kid like me.

The days of handballing heavy bags of feed were already long over and the only way to survive was to either upscale onto lorries and forklifts, or else focus on higher-profit accessories and supplements.

and weekends and busy times like September an

had kids and her husband took over. She was seven months pregnant and lifting bags of horse feed on her shoulder into people's cars.

and banter quotient was something else.

There weren't enough people in the village to support a shop, but farmers

We never had many foreigners because none bar Brits lived in Ireland until the late 90s, and those that came weren't entrenched enough in the land to have animals.

Anybody can have a dog, whereas horses only belong to certain subg

so we'd get suburbanites from Lucan and Celbridge

between local farmers, horse people from up the mountains, horse people from the estates in Clondalkin and Tallaght, travellers in

I presume the latest batch of blow-ins have begun to outnumber the old divisions, between the old village and Mayo people planted here in the 1950s, including the family of Mary Harney and her cattle-farming brother Lar, wearing odd wellies

McEvoy's old thatch pub burnt down, just as the Polly Hops in Peamount did before it. The underpopulated village has finally been filled in, with houses and shops finally fill

I'm warm enough and soon the wind will be on my back as I start to arc eastward. This used to be my cycle route up to my dad's shop in Newcastle for all the summers I worked there, and\
It occurs to me the there ought to be a cycle land

\- My mam is out for her much-needed morning ramble.

\- He lives in the moment, unconcerned for the past or future, like an accidental Buddhist monk

I remember when it was all just fields

Tubber Lane

\- Covid lockdowns

\- Trips with the baby on the bike,

\- Photos before it's all gone

\- Cillian Ryan lives here

-   Laundry went missing

-   Probably a legit mistake dbf,

-   But he was somehow wearing my same lime and navy t-shirt some time later

\- Aderrig Parish

-   Remember when I

\- Back roads

\- Arthur's Way

\- Dog on the corner, running after me every day

\- Think of the fella who cycled from Ireland to Japan and the scariest part were packs of dogs in Romania or Bulgaria

\- Train view

-   Can see the little known hills of NorthEast Kildare

-   Hazelhatch McEvoys

-   Boat people

-   Seems lime more than there used to be

\- Danny Janssens

-   Niece married to my mate's brother, the sort of rural interconnection that I've never really had

-   The pleasantness but not of the nastiness of the Irish (?farmer?)

-   Belgian planter

-   Sense of humour 5% off

-   Compare Al Nolan

-   N

\- Newcastle finally being filled up

-   Everywhere gets it eventually

-   This whole cycle will be impossible in a few years' time

\- Dad's shop

-   Babs, zig&zag, Trish

-   Dick Smith,

-   Watched the solar eclipse with him in summer of 1999 squinting through a broken piece of welder's glass

-   House opposite knocked down

-   Rumour was that the priest lived there with a housekeeper locked upstairs

\- Newcastle Rathcoole Gap

-   Filled with industrial estate slash business park shite

\- Texaco

-   Lar Harney, Mary's brother, would go in, wearing odd wellies, and stinking of cattle shite and kids would run away from him.

-   Meanwhile, Dora, and early adopter of high-end stuff like sandwich delis, battled hard to keep the place clean and I still hear her scolding voice in my head every time I want to park my bike against glass.

\- Left for Sagart

-   Coffee

-   Regular stop for me here

Slade Valley

\- Top of a hill

\-

People often wonder what comedy will be like in a post-woke world, but Big Val has long since nailed it, as his humour is based around absurdity and impossibility. The only time it ever went wrong was when my mam was doing a raffle and a possibly deceased artist donated a painting. The daughter called soon after and asked how much it fetched and my dad jokingly said a million quid. The problem was that the daughter had been waiting a long time for this day to come and so my dad felt McGotes Orkwo, something that never happens to him.

His personality ought to be captured through actual speech, not explanation-y stuff

\*\*\*

There are a few hundred metres in Kildare which I couldn't avoid

somewhere on the coast where you can cool off with a swim if the descent

before descending to the coast

for a swim in whichever part of the South Dublin North Wicklow coast line that which ever part of the SDNW coastline you like,

\- This is clearly how the lads in the Giro felt every day this year in the wind and rain and cold for three weeks solid.

Stop on the road to Johnny Fox's - cyclists asks if i'm ok and he probably realises I'm worse than I realise (wording)

\- i say i'm just wrecked

\- but i realise after i must be dehydrated, although later on my wife suggests I might have mild hypothermia. I

\- the next 8k are heavy going but

\*\*\*

I stop for peanuts and a date and I could do with more but I punch on. I'm nearly out of water now too which is a worry.

\- It's too rainy for people to stop and talk and anyhow they all seem to be the self-loving city types who don't engage with strangers.

\-

Glenasmole

\- The climb up to the Military Road undulates and it's hard for me to get a rhythm, especially with my tiny range of gears (explain). These old bikes weren't designed for rampas r

\- Some parts are fine but some ramps are 14% for a few hundred metres and it's not easy to drag 93kg up there and while zigzagging helps, the roads are so narrow that it's hard to do

\- I was up here with Kilroy early in the summer and he nailed it straight off while Blue Thunder's gearing broke several times so I had to dismount and fix it.

\- When I get to the top of the wall, car stops to let me pass and as I signal, he gives me a little clap and I break into a huge smile which gets me through the next few hundred metres, yet the climb just keeps on frigging going.

\- I have to go deep but again the lack of rhythm means I can't find it. I remember previous pains like nasty training or the horror of suicide when people can't keep going and that urges me to push on, and then I find some horror in my own family life that gives me that last push. That's my well and that last set of circumstances is added to the pile that I can refer back tot he next time.

\- At the top, the road is frighteningly windy, like don't go cycling windy, but my only choice would be to descend from whence I came and not complete today's journey. So I punch on and the cold is in me now. I stop off a the viewpoint and take a quick snap of the city below, and I descend further towards the veer-right to Johnny Fox's. I've always loved this valley cos you are up the mountains but not climbing so it's rewarding and beatiful without being agonisingly difficult.

\- I stop for food

\- Yer man etc.

\*\*\*\*

Johnny Fox's

\- i get in and order a pint, a coffee, some water and crisps. I badly need a meal but I don't have time with the light fading. Luckily people vacate the big table by the fire so I set up camp, and hang my windbreaker and shoes on the grill to dry out, then I put my back to the fire, angled slightly towards three ladies having the lolz cos I don't want to ruin their chats with my misery.

\- The place is too busy to be a refuge but it works because squashing people in tightly provides a good substitute for atmosphere. EXPLAIN

\- I'm in no state for joining anyone's conversation, nor to soak up minor variations among the tourists, bar the Yank Boomers out front, talking about the joys of massive rental yields, par example.

\- I ping a lads' group on WhatsApp to see if anyone is round for a pint in an hour and I get one biter so that gives me (?)solace.

\- Reminder of Black Tuesday in Maam's Cross and you appreciate the comforts of a house. Me and Jasper joined Leonard, Mary and Morto who were yomping across Ireland from Dzublin to Galway and on to Achill Island. We teamed up on the bleak side of Galway, setting of from an outhouse beyond Oughterard and decided to cut across country to Maam's Cross.

\- It was June 2006 and it had been raining for two months. The first couple of miles were through a forest and it was mellow enough to play talking games, and then we hit open country, where the Western Way was marked with wooden pillars and a sign saying the Way was closed. Arrogantly, we marched on, and nine hours later we had covered the nine miles of rocky, wet, exposed terrain, and we sat in the boozer for tea. We still had to walk another thirteen miles on the road to Leenane, where Leonard and Mary treated themselves to a B&B while me, Jasper and Morto had to pitch a tent inside one of those green deserts made of conifer trees.

\- I learnt that day that the West of Ireland is best experienced behind a window, either in a house or a car.

\- I leave Sharifa a voice message as soon as I step out of Johnny Fox's but it's a bad idea cos the cold and pain are hitting my body as I speak. On the tricky descent, I see Killiney Hill and Howth Head at once and it's a siblingship I hadn't seen or at least noticed before, two humps marking the boundaries of Dublin Bay. I chicane through Kilternan and then down the bendless shallow descent of Ballycorus Road and the pint in my system makes me feel nineteen again, unfrightened and at ease with myself and the bike. The road from the N11 rising to Killiney Roundabout is as good a set up as you'll get on a bike lane in this country, and then I discover a bike lane hidden behind the trees on the road down to Glenageary-Dun Laoghaire (check). It's a good thing cos it's getting dark now.

\- I'm tempted to sit down for food and a pint now cos your man should be here by now, but I decide to nip down to the lighthouse first and tick that box. This turns out to be a good decision cos it's actually a 3k spin from the Dart Station to the end of the East Pier, past a boatload of sailing clubs. I ask a lady if you can traverse the pier and she says 'not on a bicycle' in the scornful manner typical of passremarkable Irish mothers. There are quite a few walkers out and some unleashed dogs convert it into a slalom course. There are two levels to the pier so the lower one - maybe seven metres wide - is slightly sheltered.

\- The lighthouse is a lot more beautiful than I had expected, its classy stone (CHECK TYPE) complementing its beautiful green glow in the last of the gloaming. Dun Laoghaire looks resplendent with its tall church tower and town lights, while the mountains and clouds behind harmonise in shape as is their wont.

\- I cycle back into the fierce breezed but I'm feeling good now. I check my messages and it turns out that your man had been replying to a different pint request so I'm back on my Tobes now. I want to get some pub grub and a pint but I've no recommendations so I end up going in and out of several boozers hoping to hit the jackpot. In the end I have to a have a scabbyass chicken burger in the appropriately Lighthouse Bar, which tries to be all things to everyone, except for scabby people who don't want to pay an extra 5.50 for some skinny chips with their 12.50 haf

\- Afterwards, I stall it back to Dunphy's for two swift ones at the bar and I hear all about Johnny from Ballybrack's dogwalking schedule, then I'm back on the Boola Dart where the ticket inspector has kindly stored my bike. In my carriage, there's a horrendufied young wan from Donaghmadourravit, screaming into her Tony about being left all alone in Dun Laoghaire and how she's not responsible for what her little brother does to the people who left here stranded. Thankfully the Maynooth train is delayed so I can jump straight onto it and home by eight where my wife has cooked some roast beef and mash, and gives me a blanket to warm the fuck up.

------------------------------------------------------------------------

The blackcurrent bushes in our garden - and now my sister's too - derive from Coolmine estate, because before it was turned into two schools and a leisure centre in the late '70s, a fella he knew told him to come over and grab a few plants for himself.

and in fact my dad remembers when it was all just fields. He used to come here to assess x

as, when it was being sold to the presumably council in the 70s, someone told him to come over take the bushes.

which was, to be fair, tastefully turned into a leisure centre, two schools, and the Millenium Park, and ancient yew trees and giant sequoias

estates unless they are your own for there are no shops or facilities within them.

and my dad used to be out here assessing weeds among the crops and advising farmers on how to #spray them

Dogwalkers and cyclists

over the canal slash trainline and then down to the Strawberry beds via

Blanch

\- Canal greenway

\- Diswellstown

\- Rugged Lane entrance

\- Paved now

\- Backed up on the Strawberry beds

\- People think that Blanch is near Lucan but it's actually 10k across a steep river valley

\- Or else across the M50

-   Pay six nicker for the #privilege of dropping dinner over to my folks

**The reason we've been living in Blanch, apart from housing-crisis desperation, is the fact that it's psychologically quite close to my family in Lucan, travelling between them is a joy because**

------------------------------------------------------------------------

\
The first part of the journey requires me to get to the Liffey from my gaff in Blanch, so I drop the same perpendicular as in the Poolbeg chapter, from the Snugborough Road Extension over the canal slash train bridge in Diswellstown, on the Blanch side of Clonsilla, and on to the Porterstown Road which skirts the top of the Liffey Valley.

One curiosity is that there have been roadworks here for like a decade, opposite the Maccie Ds ever since someone drove into the old demesne wall, and no one seems to want to take responsibility for fixing it. Perhaps the council are waiting until they own the land and can extend the demesne into the village and a path of **interacting life** can be restored to the river in parallel to the siloed dualler atop the esker above.

------------------------------------------------------------------------

------------------------------------------------------------------------

This time I turn right, after descending the freshy

It's the reason why Castleknock has maintained its high status

INSERT HOUSE PRICE MAP OF DUBLIN 15, IN QUANTILES, WITH MEDIAN DUBLIN PRICE LINE ACROSS IT.

***Yr.no*** **says the wind is travelling at six or seven metres per second but that's a unit I haven't internalized at all so I need to convert it into kilometers or even miles per hour.**

The 20kph wind is in my face on my way to Lucan, but I'm sheltered by the trees between the river and this blissful road.

. I start out the same as in the Poolbeg chapter, rolling down through Diswellstown and Rugged Lane to the Strawberry Beds, but turning right this time for Lucan village, not left to Chapelizod. Six Degrees Celsius is also not a fail. I've discovered that temperature in Fahrenheit matches exactly against University grades.

40°F = 4.5°C, a third class degree, the barest of passes. Wear your coat and optional gloves.

50°F = 10°C, a Desmond Tutu. A bit crap but acceptable. Wear a jumper

60°F = 16\*C, a II.1. A good degree. Wear a t-shirt

70°F = 22°C, a first class degree. Do as you please.

but I feel well wrapped up and my thermal gloves complete the job. There's a cross-headwind but that won't be for long.

This is a home fixture for me, at long last, but it's funny to stop and take photos of familiar sites.

\- Lucan village

-   Weir, near flooded

-   Fella there who says it burst a while back, up towards the apartments

-   We reminisce on the flood of I think 1992 when the Griffeen burst and flooded Kenneys and O'Neill's pubs. He was in there that morning and I ask him if he was still going or getting started and he says he was in for a cure

-   That day was one of the happiest memories of my childhood as me and my dad went for a walk together to scope out the other flood point, near the entrance to the Demesne, where the NAME RIVER converges with the Liffey.

-   In my memory, it was Saturday June 16, 1992, and Sports Day in school was cancelled, so we all came home from Boarding School for Half Term \[it was actually 1993\]. Me and Big Val brought a disposable camera, which was something you only did when you want on like holidays, and I remember being distraught when they didn't develop properly.

-   I point out that it's a pity this chunk of river is set off from the village but your man reminds that me the council has bought the land off the Italian Embo so we'll be able to walk through it and connect up with the Lucan demesne and on up to Leixlip. This, I point out, will be an important step towards putting in a #greenway all the way in to town, and my brother-in-law only suggest the other day that Shackleton's mills might be restored as a tourist spot, given how darn famous Ernest Shackleton is. Your man makes the point that there should be space enough for a big car park in the Embassy grounds and that will take a lot of the misery out of the village, which is beautiful but nothing like as well-used as it could be.

-   It's nice to talk Lucan for once.

-   I grab a jar of jam for my folks from a regular street vendor outside the Protestant Church

-   Hub by the BP

\- I can hear Yo la Tango singing My little corner of the world

\- Dad's shop to the left

-   Avoid cos the main road is so shite

-   Also I have come to think that this junction is a natural

Drop in to my folks.
