---
title: "Wicklow Head"
editor: visual
---

Ashford

-   a real two accent twos

-   local accent, like #RealDubs, have been speaking it since the Normans

-   and sure envough

0904, Monday, Jan 16, 2023

It's Martin Luthor King Day, and because I work for an American company, I'm offski for the Doris. It might be unpaid but these American bank holidays are a special kind of me time you don't normally get as a 9-5 drone, because when we are off, so is everyone else. So I cycle to school with the young lad running beside me, and then I'm free for the day. The problem is that it's proper cold for Ireland and I'm trying to scope out how icy it is. It's only zero or one degree this morning, rising to just three degrees by midday, and I suspect that it'll be a smidge colder up the Wicklow Mountains. I'm heading to Wicklow Head today, 56k south of Dublin city, and I could buzz into town and take the flattish route via Bray, or I could take the fun route over the Dublin slash Wicklow mountains. The problem is that if it's a bit icy here, it's gonna be an ice rink up there.

I'm gaggo to go over the mountains because I love it up there and it's the only chance I'll have to write about those mountains in this book. My guess is that it'll be icy on the Dublin, aka north, side of the mountains, and that once I get over the first big peak the sun will be melting any ice. But I'll have to take it very easy on the descents, which doesn't bother me cos I'm plenty scared at the best of times. You wouldn't get much mileage on the bike in Ireland if you worried about inclement weather, but safety is a different matter, and heavy winds or ice are real reasons to stay off the bike. Having said that, I have work to do, getting to this lighthouse *and* taking in the mountains, so I'm pretending to myself that it's ok. It was only afterwards that I found out there was a [status yellow ice warning](https://www.thesun.ie/news/10057298/snow-ireland-gardai-travel-warning-january-freeze-met-eireann/) overnight, with special mention of the Sally Gap, although they expected it to pass by noon.

Getting to the mountains from Blanch is a pain in the gulags and it's yet another reason why I miss being in town. From the city centre, you can warm up on your way to the mountains, take in a good climb and then roll home, all within two hours, and quicker if you're pushing it. I make my way to Chapelizard and then up the steep hill to Ballyfermot. I spent a year doing this route, between the bike and the car, lugging my son to creche in the morning. ..... a place I spent a lot of time in the last couple of years, as my son was in a really great creche there, Teanga Beo, where the kids could buzz about inside a sea of love from the staff. We used to live in Kilmainham before the landlady decided to flog the gaff and the housing crisis forced us to emigrate to Blanch where we know no one. So for twelve months I lugged him over by car or bicycle and my wife picked him up on the bus after work. It was a trek but at least we kept a little stability in his life while he was one the many children whose early years are ruptured by this country's failure to provide homes for people. We'll be moving again no doubt, once we have saved up a deposit to buy our own home, another sub-scandal in itself, and a big part of today's trip is to check out gaffs in South Wicklow which we might be able to afford.

I misjudge the diagonalization from Ballyfermot to Rathfarnham so I have to cut back across from the Walkinstown Roundabout towards Terenure and then it'll be a straight shot up to the viewing point in Killakee.

Before I start climbing I have to stop off in a chemist to get an emergency ventolin inhaler because my lungs struggle when the temperature drops this low - I'd say it's about two degrees now. The pharmacist takes forever, like a solid twenty minutes for one item. I can never understand why pharmaceutical companies can put so much ingenuity into creating miracle medicines yet no one has worked out a way to dispense tablets quickly. Surely the back of the pharmacy should just be one big vending machine, supervised by a pharmacist who can talk to the customer. Instead, they piss away their time and yours by counting beans in the back while front of house is occupied by non-specialists who either don't know anything or aren't allowed to discuss it with you.

Shorten this a lot.\
On my way, I pass the session gaff I used to live in beside the KCR junction. A couple of the lads there were in a band called Ito and they practiced in the living room and the bandmates hung around for joints and cans after. There was always an energy in the gaff and everyone was always doing something. Johnny and Steve were in the band. Imogen was a photographer. I was trying to write about the letters of the alphabet. JJ was a street performer and used to dress up as a skeleton and scare drunk people in Temple Bar. I started cycling back then, in and out of town, as we all did, cos the bus was a jake, and 5k seemed like an unbearable distance, especially on the incline home. What hasn't changed, however, is the difficulty of negotiating the traffic in the otherwise beautiful Terenure village.

After Terenure, it's the Rathfarnham and then an urban to rural continuum as the road rises slowly. Once I get under the M50 the gradient increases, 2, 3, 4, 5 per cent up to the Merry Ploughboy before cresting briefly, and it's a good chance to get a feel for where the lungs are at. To feel your first wind. I think I finally understand the concept of a second wind. When a game starts, you run round headlessly and get out of breath because you haven't yet matched the pace of the game to your fitness, but once you find your own level, then that's your second wind, an acceptable level of exertion which you can maintain. Once the road rises from the interlude valley, I need to find my second wind because it's about 3.5k at 6% from here to the turn for Johnny Fox's, with a good stint at 8-10%. It's no rampa inhumana, but it's the hill against which I can measure my lungs, my legs and my mental state. Every time I come here I have to go to the well a little bit, just to keep my legs grinding. Thinking of the late Eamonn Donoghue got me up here once, and he'd've been forty in November, God rest his young soul. My mam's illness in 2014 too. And more prosaic difficulties in my own life. Getting through the PhD and my troubles with the booze. Whatever is really wrong in my life will always come to me and suddenly I'm thinking about that other issue i have. Yet I realize that when that problem is gone, everything else in my life is now in a good place. We've got a baby on the way in a few weeks, and my wife is healthy and our son is well, and our relationship is good. My mam and dad are good and I am satisfied inside myself. Between the bike and the writing, the hole in my soul is filled, and for once I can't hear a scream, but a contented fulfilment. Nothing aches inside me and I smile ear to ear as the gradient keeps on giving. You think you are there but there's a blind bend and another steep rise, but it's all good. After the junction, the road flattens out and there's a handy 3k to go before the Killakee viewing point.

I stall the ball at Viewing Point although I don't find that it's a view which improves every time I see it. Maybe I should come here with my full-strength glasses, as my prescription shades are a notch or two weaker than my latest specs. Apart from the beautiful coast, Dublin just looks like a flat sprawl with few notable landmarks or patterns. I suppose cities are seldom designed with a bird's eye resolution, except for the likes of Brasilia, a commissioned city where the street design echoes the shape of the land.

EDIT 2 -\> Reframe that the viewing is good for understanding the lay of the land and not for specific streets etc. so the city is definde by the water and the slops, and they are not responsible for low-level deets like street layout.

I'm getting cold now with all the standing round so I push on and I hope the road is clear of ice. The first few hundred metres are through one of those dark green deserts, with unwelcome evergreen

and the evergreen trees are making everything dark. Soon they fall away and it's open space all round. The roads are clear but the grass is white with ice, the sky is California blue, and the sun is blindingly low. It's incredible. I've seen this place looking variously green and yellow or purple and red, and I've even see it burnt to a black crisp, but now it's long white streaks of ice diagonalizing out of the ground. I go round the bend and as I look back, I see the grass is all yellow. The sun has melted the ice on one side of the grass but not the other. I keep my momentum to get to the top before stopping to take some snaps, and on the descent I barely recognise where I am from how different the landscape looks, and my recognition comes from my familiarity with the bends on the road, which itself seems narrower and more cracked up than normal. There's a graveyard of trees now and each narrow stump has a plastic domino erected beside it. There's a sign saying the Sally Gap might be inaccessible in winter and there's the easy road to Enniskerry to my left, but I'm in no mood for half-arsery, nor for that fast straight descent down to the waterfall, so I punch on and I'm actually glad that there's another hill to climb now because I"m so cold that I need the hardship of climbing to warm me back up.\
\
This climb always looks less steep than it really is because it's open and roads always look steeper when there are trees or other markers to highlight the hardship, and I end up having to get off the bike at one point because it's too difficult for me. Or, more accurately, I've gone into the red because I've misjudged the difficulty. Or more accurately again, I've gotten off the bike so many times now that stopping due to pain has become a legit reason to rest. And that's yet another problem with taking snaps en route. It banjaxes your cycling rhythm and it takes your head out of the game, and your mind doesn't get to go deep inside itself, either by accident, cos you are in the zone, or by design, as in this case, because you need to go to the well just to keep going.

THIS BIT BELONGS ABOVE ON THE KILLAKEE CLIMB\
That to me is the greatest beauty of climbing, getting access to the well of experiences inside you, because as your legs struggle and your body says no, your mind thinks of something painful from the past and you use that as motivation to keep going. And now the current physical experience gets added to the well, so that the next time something is equally hard then you don't need to rely on emotions, cos you've got the bodily memory to refer back to. It is literally like *D'yeh remember the time you were on Kippure and you kept going?* And that memory tells you that you've done this before and you can do it again. When I started cycling first I had to think back to rugby training, and the pain of the drills I had done over the years, and those memories kept me going. Paul O'Connell used to always talk about going to the well, but he was talking about doing in the middle of a match, which is something I find odd, because I find rugby too fast-paced to have time to think back in your memory. Maybe he's doing it just before packing down to a scrum, or else he has game-speed access to his history of experience. But for me, I need slash love the slowness of cycling pain to help me go there. My goal is not to find the limits of my physical capabilities, but to understand the limits of my own inner self. To know who I am and how I was shaped.

It turns out I have become someone who stops on the side of a climb to take photos. I time my rest to coincide with a parking spot used by drivers to view Lough Brae, with it's steep rocky walls making it look like a big mixing bowl filled with black water. There is no one foolish enough to brave this freezing bowl of water today although I've often thought this'd be a fun place to hold a triathlon. Swim in this lake, cycle the roads and run around the gorse. I must start hiking out here too and get a different view on these hills. After all, this is a massive national park which is still underappreciated. Everyone always bangs on about the West of Ireland but Wicklow is just as beautiful and, if hiking was your job, you could easily commute here from the city centre.

I push on up the last of the Tonduff-Kippure pass, and the the land plateaus for a few clicks. Thankfully there's no wind today as this place can be devilishly cold, and the climb has my blood back moving. Bizarrely, a fella pulls up on the road in front of me and whips out a big pro camera and I give him a photobomb wave, but he actually flags me down. It turns out he's a freelance photographer - by the name of Damien Eagers -- and he asks me to double back and go again for a better shot. He takes my name and tells me he'll be sending photos into the newspapers and I wonder how they'd feel about the worst equipped cyclist in Ireland out slugging through icy roads. l push on, wishing I'd told him about my lighthouse trip, and I come to the Sally Gap, and stop at the exposed crossroads, which functions as a great endgoal in your mind and a terrible stopping point because there is no shelter. I'm trying to take arty photos and Damien reappears, and we have a proper chat this time. Before I bounce, he gets me to do another looparooney so that he can get Kippure in the background, with its snow and fukov TV mast,

One road goes to Glendalough and the Wicklow Gap, and I turn left for the Guinness Lake and Roundwood. This is less familiar territory now cos I'd usually swing around at the Sally Gap, descending towards Brittas, but it's handy enough this way too as it's mostly downhill, and I just have to be careful to dodge any ice, which only crops up when the unwelcome coniferous trees block the light. I stop off to look at the black and white lake and its teeny private flat valley and it's like looking at the past from above, when Ireland was divvied up into estates, with peasants out of view and aristos having afternoon tea in the gazebo. Some member of the Guinness family owns this land and I remember that I must pick up Paul Howard's book about your man from this branch of the family whose death was documented in the song *A day in the Life*, by The Sergeant Pepper's Lonely Hearts Club Band. I want to know more about the Guinnesses because I was friends with Patrick Guinness in boarding school and I haven't seen him since I was ten, and he was old enough to move on to secondary school somewhere. His mother, Marina, was the kindest of souls and she'd rescue foreign kids for the weekend, as they would otherwise be locked up in school for like three whole months at a time. Presumably she felt a lot of conflict between feeling sorry for the individual kids and the aristocratic habit of sending their eight-year-olds off to be raised by gangs of nine, ten, eleven and twelve year olds. I saw Marina intermitently down through the years as she used to buy her chicken feed off my dad, although unlike most customers she'd be more interested in hearing about us, rather than unloading their latest goss or personal hardships. The presence of such people in my childhood gave me an awareness of a rock'n'roll world which never seemed to seep beyond the Hidden Ireland of castles and estates. I used to get lifts home with Lester Lloyd and he'd be playing the Sex Pistols and the Stones, except that these were people who crashed in their gaffs after parties. Paddy Guinness's dad was the drummer from The Police, Stuart Copeland, but he was off in America. (SWITCHPU ORDER HERE). This world was my equivalent of Seamus Deane's childhood memoir, *Reading in the Dark*. He only had an oblique access to the brewing tensions in pre-Troubles Northern Ireland, while I had an oblique awareness of a life of music and parties and people with funny accents and funnier friends. In secondary school I stepped sideways from elite protestants to elite catholics, from people with land and rundown cars to people with well-paid day jobs and proto-Celtic Tiger flash wealth.

It feels like a part of my upbringing and identity never got manifested and there is a huge gap between the per

I need to go back understand the world from which my schoolfriends came from but I

------------------------------------------------------------------------

The descent transitions from mountain bog to farmland and I emerge on a a busy one-way rural road that is the worst kind to cycle on. Cars zip by at the limit slash recommended speed of eighty clicks a Paddy, and when you're not getting overtaken at breakneck speeds, then you're in a tractor's cavalcade, **rubbing wing mirrors with angry lokes**. It's only 3k to Roundwood so I stick it out and I'm curious to check out this village, seeing as I'm kind of on a mish to scope out South Wickow as a viable and affordable place to buy a house and live. Instead, I follow Google Maps and a rare pedestrian who both guide me left towards Ashford just before the village of Roundwood reveals itself. I know I've missed a beat cos I remember me and Mono stopping here for a carvery nearly ten years ago and watching Jimmy Gopperth missing an extra-time dropgoal by a cunthair, preventing a particularly unmemorable Lonster team from reaching another Heineken Cup Final. Such are the hashtag margins. But as I say, I'm on a mish to check out a few villages and this is the one I'm least interested in, being a piece of the midlands which has leaked into The Garden County.

It turns out that the Wicklow Mountains are not quite parallel to the coastline, and Roundwood and its lakes lie in a bit of a plateau between the mountains proper and a harmonic overtone of hills through which I'm about to pass on my way to the coast. For a few clicks, I'm back in the Ireland I've never had much interest in. Lumpy fields and nothing happening. Supposably, this is idyllic and I can even see why Kim and Kanye took [their honeymoon in Offaly](https://www.dailyedge.ie/kim-kanye-honeymoon-ireland-1491019-May2014/), but to me it's just livestock and jeeps, an outdoor factory for churning out nosebag, and you're not welcome, unless you are on tea-drinking terms with the farmers. From the viewpoint of someone squashed into a shitbox duplex in the burbs, it's an extraordinarily inefficient use of our beautiful country, and I wish we could find a better way of divvying up the land between the need to accommodate people, the need to produce food, and the often forgotten need to reforest the island's natural habitat for the poor bastids who got turfed out.

Soon I'm back in the hills, signalled as much by the presence of equestrian centres, as much as the slight road gradient, and around a bend the coast reemerges in the distance, giving me its spacious calmness as well as a sign that I might soon reach my destination. The hard work is done and this trip is now about exploration, looking at housing developments and getting the lay of the actual land. We're talking Ashford, Rathnew and Wicklow, where new homes still cost less than 400k, and I can find that magic mix of the sea, the mountains and, I hope, a community for my family to be a part of, even if that will always be a little alien to me. EDIT EXPLANATION\
\
As I arrive in greater Ashford I'm greeted by New Homes on both sides. I recognise the name of one of the developments and go in for a quick spin and there's about a hundred cookie-cutter Roisins with a lump of grassy soil in the middle. I want to cycle round the path at the back but the pavement is five or six inches off the road, and I can immediately see how this will be a problem for kids cycling round. It's not a dealbreaker of a problem but it does show how little care goes into making housing estates habitable. I feel like I need to do a tour of the world before I come to understand how it ought to be done, but I'm a hundert percent sure we're doing it wrong in Ireland. There's a larger development nearby and each house has an actual upside down cross under the gable roof **(wrong words to describe this part of the house)**, and I feel like I'm in a horror movie in the Deep South. I make my way down to the village via some roadworks and I'm delighted to see that these developments are only a five minute walk from the village, exactly how I'd like to live.

I see a charity shop and I go in and buy myself a light fleecejumper for a fiver and it makes a big difference. The lady's accent is very posh but not quite West Brit and I'm like this is going to be interesting. I go in to the cafe next door, *The Hen and Hog*, and I quickly clock that this is a two-accent town, exactly like Dublin city, and the name of the cafe kinda describes this. You've got your ancient accent dating back to the medieval English brought here by the Normans and this is only spoken by bonafide locals, of the right -- or wrong - background. In Dublin, they are condescendingly called Real Dubs, although that sounds aspirational to me, as it's how I'd like to describe myself, seeing as I couldn't name a single distant relative born in the other thirty-one counties of Ireland. But my people don't come from the old city. Then you've got your West Brit accent which came in centuries later and modern blow-ins develop gradations off that. In Dublin that has ended up as the D4 accent among younger people, but as we heard in Seapoint, it's less consistent in the older generation. **It seems to be same here, with David Attenborough being more of a reference point than ...**

The lady next to me is telling her lunch companion about laast week when she went awf shopping in Dun Laoghaire, and meanwhile the waitress is saying sarry she took so lo-ong, it's only her first da-ay, in that down-to-up accusing tone that Real Wickla people have, although I don't know what they are called.

The village here looks a nice size to live in. Enough going on to keep you fed and watered and the kids in school, but definitely not a town. By the time I leave, it's like school collection o'clock and there's a logjam

it's clear that this is a place in flux.

------------------------------------------------------------------------

I was schooled in but not familied inadjacent to

was only obliquely aware of the tensions in pre-Civil War Ir

whose dad was the drummer from The Police, Stuart Copeland, and whose mam

whose name sounds like it was designed by a tourist who had never ventured beyond Carroll's Souvenirs. Paddy's dad was the drummer from The Police, Stuart Copeland, and their family were part of a rock'n'roll world which seemed never to seep beyond the castles

Paul Howard, I read the news today

Patrick Guinness, Stewart Copeland, Marina, house a refuge for kids and the land for travellers, now Kila etc,

Dad used to sell chicken feed to Marina

Adjacent to this world as a child but never understood it. Lester Lloyd. Dire straits, money for nothing etc. Rolling Stones

https://www.irishexaminer.com/lifestyle/arid-20438101.html

\

A notable contrast to this is the equestrian centre, which remain social hubs, where ladies in jodphurs intersect over horses and Jack Russells, and the whole gig is a legit throwback to the Dorises when life was centred on the estate

and the last time I was here there was a brave soul hardy enough to swim in this freezing bowl.

. This must be how it feels to live in a place with four distinct seasons

although from this vantage point it is easier to understand

\
\
it's not a view that improves with

It's too hard for me to yap and it's too har

The difficulty forces me to look inside myself and

If I"m with someone, it gets too difficult for me to yap

It might not be the toughest hill in the world but it's my measuring post. Like the Liffey River. Anything wider and it's a big river to me. Anything skinnier and it's small.

------------------------------------------------------------------------

bounced around thanks

that's how we ended up emigrating to Blanch where we know no one. Our spent t

which feels like a holdout from the days when no one moved to Ireland.

I spent a year doing this route, between the bike and the car, lugging my son to t

This means you can hit the mountains before or after work during the summer, and getting there is a

do a two-hour cycle out to the mountains, get a good climb in, and then roll home. And if it's summer time it'll be bright enough to do it before or after work.

It's only as I write this on Tuesday morning, January 17, that google is sending me links to the yellow weather warning

Bad weather on the bike doesn't bother me but ice and heavy wind do because the bike just can't handle them.

get a feel for the ground. It's zero or one degree this morning so there's good odds that ice will be around. I'm delighted that thee

and it's a great chance to get out on the bike. Wicklow Head is well doable on a day trip and it's a grea
