---
title: "Ballinacourty, Dungarvan"
format: html
editor: visual
---

Lighthouse Pete told me to check out the Metal Man in Tramore because, as a lighthouse with no light, it brings a little variation to the genre. I met him for a Britney in Clonee the other day, partly because I've been meaning to for ages and partly because I now need his help in planning out the more complex trips along the Atlantic islands. He's a self-confessed anorak who has now spent longer blogging about Irish lighthouses than he spent going to punk gigs in his youth, and he gave me a copy of his oddly charming book about fatalities in and around Irish lighthouses between like 1750 and 1920. He's tapped into the fact that lighthouses provide a direct connection to how life used to be in the rare aul times. Maybe It's just me, but I find it much easier to imagine a child falling off a cliff by a lighthouse than to imagine the poor sods dying of dyssentery in the tenements.

although I can't imagine there would be many people who wouldn't ca

although as a lighthouse blogger, it's fair to say anyone

Tramore

Pissy grey day and I've been too scared to look at the forecast. Gearwise, I've got my shit to-prettymuch-gether, after the frozation disaster the last day. I stalled it over to Decathlon to kit myself out in warm clothes and I got some help from the son of an ex-pro, Paul Butler. I'm wearing a skintight bodywarmer base layer with chest padding, which is the permanent version of shoving a newspaper down your jersey, and a wine-colored outer coat which looks like a red leather jacket I picked up in actual Dalston during the peak recession, peak Dickhead era. Before hipsters were even known as hipsters? I've actually lashed my yellow jersey on top for visibility, maximising the Italo disco slash gaybar vibe which you can either

ex-pro, Paul Butler's son who does a good bit on the bike himself. He kitted me out in 've actually lashed my yellow cycling jersey on top of that and then I've gone and ruined the Italo disco gaybar vibe by lobbing a shoddy windbreaker on top, doing squat for my image and visibility.

the full Italo Disco slash gaybar vi and the gaybar vibe is ruined by

then I've got a windbreaker on top again doing nothing for my image or visibility. The thing about cycling gear is that when you do go for it, you can go big, so if you look like you're ready for a night of Italo disco in a Hi-NRG gay bar, then you just gotta own dressed for a gay bar had during my peak recession, peak

To the metal man glorious swimming spots one for the hardcore swimmer who dive in off the rocks and another round the corner for casual bathers. A lovely tiny cove that would be a great spot for a rave.

The coast road from Tramore to Annestown is great cycling country but the coast road is actually through a buncha farms, not along the sea, a problem that arises from the shape of the coastline ﻿Plenty of steep hills though

Good chats around here less need to stop talking about Marketing etc.

PHOTO square farmland

Copper Mines

A treasure trove of coves

Narrow valleys Steep entrances, imperfect beaches

Bunmahon

It's time for some scran

We stop off for coffee in Gourmet House cafe,

Coffee's not Graham's cup of tea so he orders the latter and we ogle the delicioso cakes. His belly screams less than mine so he orders a carrot cake, while I'm trying to work out how to hashtag get the protes in, but the only nutty offer has peanuts and honey, a combo I maxed out on as a sprog, so I choose a homemade bounty bar, which is deloosh, and we get some Fulfil bars for sustenance.

The friendly lady behind the counter asks about our accents, which is easy for me although Graham keeps his gob shut. We tell her we're checking out the coast for the Doris. She goes straight into tour guide mode, extolling the virtues of coastal living and I'm just there, thinking, "Yeahno, nono, no I know like", cos she's preaching to the converted and I'll be moving to Wickla any week now, with sea views in the morning and saltwater air in my lungs, once the solicitors bother their Gordons to push their pencils in harmony.

There's a photo on the wall of the copper mines, with prospectors dressed in splendid white and knackered miners in the shadows, the lot of them united in their spendooferous moustaches. It doesn't look like a scene from the Island of Ireland, and I ask Orla where they all lived, because there's no evidence of them left and the info board said there was up to 2000 of the beggars at one point. She says they lived in a shanty town and all that survives are some houses for the prosperous, a group she seems to identify with.

Yet she tells us a story from the Famine when a poor woman had to trek here all the way from West Cork with her seven children - fully two hundred miles - and she lost three or four of them on the way. When she got here, she found her husband dead too and after that she lost her mind. This reminds me of the time me mam had an undiagnosed bout of mania after cycling around Northern Spain on her Tobler, not long after her mother died, and now Orla is sitting down, telling us of her own grief, of her father who died last year. We are int he depths of it now, and Graham tells us of the shock of his father's death, and how long it took him to come to terms with it. It's not the time to tell them that my dad's nickname is Lazarus, but I do feel grateful that he has his health - ish, like.

Orla helps us plan out our route to the lighthouse but she has us doing doublebackarooneys just to get extra clicks in on the famous greenway, so we decide to turn left for Stradbally, up a steep exit hill. On top is a chunfla with a smirk on his face, and further down the road a farmer greets us twice in a manner that comedians often talk about. First up is a warm greeting as he gets out of his jeep and a moment later comes that same smirk, laughing at our silly efforts to take on this supposedly forbidding landscape. It is a theme of the day, as every village along this coast sits in a gap between cliffs so the only way out is uphill. We had it in Tramore too, and Graham realises peple think the same in Dunmore too.

As we approach Stradbally, there's a fork in the road and we elect to do another down and up via Ballyvooney beach. This turns out to be one of the great decisions

Orla tells us tyey

lady in tourguide automode took a while to shift her to real when talking abouth er own father, her grief, died last year

Mutual Masturbation

logrolling? she tells me to send on some stuff that she'll post it on Instagram and of course I'll be doing the same, putting a word in for the cafe, and it's the first bit of mutual marketing (masturbation) that I've been involved in, an insight into the bigeachotheruppery that feeds so much #content on the Jimi Internet. I'll wank your sack if you wank mine Afterwards, Graham tells me a bit about his own efforts to employ #influencers to promote his nosebag and the difficulty of getting converting people who land on your website WORDING his issues are the kind of thing I could do with some practice with, as a data analyst in search of work

Stradbally

Out of Ballyvoo?? cove, don't bother with Stradbally village and the supposably coast road is now a lush thin valley that screams Protestant Estate. Sure enough the Big House pops up and the entrance gate is a thing of beauty, although I wouldn't be surprised if the place has been flogged off to some Continental magnate with zero relationship to the community.

**Greenway**

Amateur vibe, which is great, if that's what you're into, but coming off the road makes it seem aggressively pleasant, like California. Families are out in force, couples, joggers, dogwalkers, and the odd Italo Disco fan whizzes by. One young lady looks like she has been re-animated from a photo on Instagram. And one couple give off a whiff of perfume, which is a first on the bike for me.

Beware of the dog. It won't be long before they have to introduce updated road markings to help everyone negotiate the route, and the staggered red gates are a valid first approximation at solving the problem of slowing down cyclists at the many crossroads, although unleashed dogs remain an issue as they simply do not understand how bicycles move.

﻿The cycleway itself follows an old trainline and it is as unimaginative as any motorway. For the most part it is just a narrow tarmac road with hedges on either side, and the beauty only comes along the bridges which cross the gorgeous valleys below. I am reminded why I much prefer cycling around back roads than walking through parks, because back roads follow the natural topography of the land, albeit with input layer of farm ownership on top, often forcing road users into horrenjus looparooneys. b results in a one-ness with the landscape that is seldom recreated from the simple geometric drawings upon which parks are built. The road around Ballyvooney Cove follows the path described by a half-eaten Pringle, better known as a truncated hyperbolic paraboloid, a shape you'll see on the roof of modern sports stadia. https://londonist.com/2015/07/anyoneforpringles Nobody would design a cycle path in this shape, but generations of goats and farmers and swimmers and anyone who wanted to pass through here have hacked out a ridonculous but necessary path which brought me great joy.

Nobody would design a cycle path in the shape of a truncated hyperbolic paraboloid - that's a half-eaten Pringle - and yet that's the shape the road must follow around Ballyvooney Cove, because God made it thus.

s a reminder that the organic emergence of back roads, following the natural topography of the land, is so much more beautiful than I don't always like parks because their simple geometry highlights usually

https://loneswimmer.com/?s=project+copper

We get to Clonea Beach, where two daytripper ladies are out posing for their camera, and another sits on the beach. Lighthouse Pete says

Lighthouse - Private, large garden, - could do with a lawnmower bot

Lunch

Golf resort hotel Bar man wondering if I was involved in the 10-mile John Treacy run (check). Bank Holiday Weekend vibes not really happening but the place is jammers for carveries, between young families looking for some respite, #lads out for trying to dose up on calories

run on in Dungarvan

------------------------------------------------------------------------

It won't be long before the level of and if you ever want to Beware of the dog then this is the place to do it.
