---
title: "Dun Laoghaire 1"
editor: visual
---

**o the lighthouse III/IV**

\

Notes

\

0805, Sunday January 1, 2023. 

\

**Getting off the mark**

\

It is, as always, a slow start. You want to be gone but the bike says no. The back brakes are banjaxed, which I can live with, and the fancy mudguard is dislodged, which I can't, cos it's dragging on the wheel. I've been tying it up with a phone charger but that's knackered now and so I need to dig out a longish bolt and *two* nuts to tighten it into place. Then I oil the chain and do a quick circle around the parked cars to spread the oil across chain and cassette but the chain pops out in the bottom gear and the dérailleur is in the spokes and I'm at my wit's end with this bike. This keeps on happening when I'm climbing up hills. It did me in Chapelizard last week and it did me in Rockbrook a while back when I was testing out whether I could climb a bit of a mountain on it, partly out of curiosity, and partly to piss off all the allthegearmenthemselves who forget that the mad bastards were doing the Tour de France long before carbon frames were available on the bike-to-work scheme. I bumped into Alan Lewis in Terenure on my way up and he was like, you're not going up there on that are you, and that gave me the extra urge of defiance to make it. But the chain was having none of it and I had to abandon my climb at Mount Venus Road cos I had to get back to pick up the chunfla from his babysitter that morning. 

\

 so I couldn't plough on when I did get it fixed. I brought the bike in to Paul on the Quays to see if he could tune it up for us. He took one look at it and asked if the chain was coming off and I said it was. He said these Pendleton bikes are just badly made but he was too busy to do it there and then. There was another lad working with him, a fella in his possibly fifties who I assume was Ukrainian, cos Paul's been kitting out donated bikes for refugees ever since the war kicked off. 

<https://www.irishtimes.com/news/ireland/irish-news/dublin-bike-shop-seeks-mechanics-to-help-with-repairs-for-ukrainians-1.4865537>

I might just have to bring it in to Halfords where I bought it in haste last Christmas for my missus, but I don't like the look of the mechanics in there, nor the looseness of the brakes when they gave it me, so maybe I'll stall over to Decathlon in Ballymun and see if Luke can sort it out, cos he's the kinda lad who can both fix a bike and help you learn more while you're at it. It's not easy to find mechanics who help you learn about the problems so you can deal with them yourself next time. Either they are too arrogant or else they want to keep you ignorant so you keep coming back. But it's my experience that the more I learn about bikes, the more I need help, cos I now have more bikes and a wider set of problems further down the system. 

Anyway, I eventually get the chain back on and the mudguard screwed in and I'm away. I can see why the pros have a whole team of mechanics and even why touring cyclists often need a back-up team. You just piss away so much good cycling time getting the bike in order. 

\

\

For once I know where I'm going. Dun Laoghaire lighthouse, or at least one of them. I head straight to the N3 cos I know I'll see the low sun there, instead of it being obscured behind houses and trees on the quieter roads, and it's a, eh, Bank Holiday Sunday today so everywhere will be doubly quiet. The mudguard has already started to come loose and of course it's because I've forgotten to tighten the two nuts so I have to dismount and tighten them with my fingers just. Sunny Cabra is looking particularly good and I flirt with finding the best spot to capture its tree-lined radiance but I start getting pissed of with all the stopping so I don't bother. It's plain sailing as far as the quays from here, and I roll through Stoneybatter all the way to the James Joyce bridge on the Liffey, which really does look, at least from this angle, like the open book it is supposed to, and more tantalisingly like the inner thighs of a supine lady with splayed legs. 

\

I turn left onto the quays and I'm disappointed that the luminescent aperture of the Liffey estuary is not bookended by sunshine, because the last time I checked, there were rays of light at the end of this grey tunnel, at this hour of the morning. But that was autumn and this is deep winter, and with the slight northward tilt of the quays, the sun seems to be hiding in the Deep South. I think about turning right over O'Connell Bridge, and actually I do, but I decide against the horrors of D'Olier St and environs because again the sun will be blocked by the buildings. So I weave along the skinny, tree-lined footpath on the south quays, using my bike's might to oust a hungover pedestrian who is already struggling to negotiate a dry passage between the wall, the trees, and the puddles that form on the ruptured concrete.

\

\

\

\

between the riverwalls and out

\

<https://drb.ie/articles/riverrun/>

\

[Santiago Calatrava](https://en.wikipedia.org/wiki/Santiago_Calatrava)

\

I start worrying about the best spot to take a photo of and 

\

\

\

 and to text him to see if he'd be free to fix 

\

\

\

\

\

Bike gears, oil, brakes, 

Paul 

I brought the bike in to Paul on the quays and, even though he won't do you, like most bike shops, he will no longer actually do the work you require

\

Bike fixing, slow to leave, see why cyclists have back up

Navan Rd, sunshine

know where i"m going

Town,\

James Joyce bridge - spine, book, legs open

Quays, flirt with turning right as the sun is in the (apparently) south

Point depot, spanner, pliers from young wan, workman, westlife et al gig, there since lunchtime yesterday, 

East Link, oul fella on bike, pass him out for the first of four times

Stopping a lot

Sandymount strand, nay cycling, Merrion Strand / Sydney parade Saudi lady with bulldog, 

Down to cycle path in park through Booterstown, 

Squidge through narrow path, pedestrian priority, narrower than two bikes

Seapoint out of habit, picnic, choice accents, This is one place I can really hide as a tourist cos everyone just assumes I'm a lake. Bike lock jammed. French ladies and their advice of oil before squeaking off on her paul van

\

Dun Laoghaire nudge down to, pier is like a 1k, coffee, chips (not open), Bryan's coffee, your man gives me some WD40 (although I ask him for 'oil'). (David O'Doherty cf).  lock bike and walk. 

\

light is good and there are some good angles for snaps (two lighthouses, 

\

Don't know the jacques chirac (at all)

Inside - magazines, ice cream, not the usual pairing, world weary, 

porta-union, 

\

\

Format is coming together

Coda piece
