---
title: "Old Head of Kinsale"
---

**Cork Harbour**

I feellike I'm getting to know the road from Wicklow to Cork now, between the functionality of the M11 and the beauty of the N25 skirting along the coast, duct-taped together by the R-like N30, and the whole thing cable-tied at Enniscorthy, allowing for a near-seamless arc around the south-east of the island.

-   There's two sides to every harbour so I'm heading back Cork City planning to head down the west side of the harbour this time. Duty forced me to kip at home last night and I was a smidgeen late getting out cos the no-longer bambino was irreconcilable for an hour. I'm getting very familiar now with the road that arcs around the south-east of the country, between the quickshot N11 and the coast-skirting N25, duct-taped together by the R-like N30 and sewn up with a cable tie in Enniscorthy. It makes me wonder if we could lash in a donut road around Ireland, seeing as nearly everyone lives on the coast. Bonus points for including a trainline and top marks if we add an extra-Large Hadron Collider.

-    It'd clean up the journey from Waterford to Donegal despite the extra distance. We could probably lob in a polyrail and maybe even throw in an extra-Large Hadron Collider while we're #atit.

-   , via Crosshaven and then on to the Old Head of Kinsale lighthouse which only lets visitors in on two days of the year, neither of which is today or any day soon.

-   Crookhaven is a haven within a haven or harbour within a harbour, cognate with the name of the Danish capital København

-   I used to think the word meant *heaven*, but that seems to have come after, given how similar the words are and how thankful sailers must be of the haven on arrival. No doubt the confusion is caused by the phenomenoally complext history of the English vowel system - see Roger Lass. But for those of you learning English who think you have two many vowels to learn, spare a thought for learners of Danish whose peninsular language has maintained twenty-eight vowel distinctions, possibly due to its never being merged with a Romance language, as has been the case for the French influence on English.

I have the lads onto My Bloody Valentine and they insist I try out Steely Dan. Now I've done my Steely Dan penance already because back as a lad, while I was monstering Can and The Velvet Underground for breakfast, lunch and dinner, I also ploughed my way through, like, *Q* magazine's Top 100 albums of all time. So I know how little I like Bob Dylan and The Byrds or anything jangly like REM's early works, and I also know how much I hate fusion wank like Steely Dan. But now, twenty-plus years later, I'm willing to see if I've mellowed out enough to bathe in their chill atmos. After all, I now volunteer my way through Tom Petty albums when I'm cleaning the gaff and The Orb have me listening to Harry Nilssen whose voice is "a direct portal to God". But the Aja album does nothing but annoy me. It's slow but there's no groove. The instrumentation sounds a wee bit complex but there's

Car journeyN

-   squeezed through the telescopic-shaped road into to Cork city, slower and narrower in phases, until you are jammed in the city's traffic.

-   It's a garjus marning in Cark, goosebumps etc

\-

-   I nip in to Avondale Something football club to watch a bunch of fellas no better than me playing ball. I'm disappointed cos after five minutes I've learnt nothing about the game. Unprompted, the fella on the door apologetically explains what I've stumbled across, assuring me that this is Avondale's junior team and the same for the opposition. It's a local derby but within an All-Ireland competition and he's clearly disappointed not to be off on a cheeky weekend somewhere far away, the kind of involuntary szechuan with The Lads that your missus can't say no to.

-   I watch for a few minutes and then the Opposition (check name) centre half hoofs the ball sixty yards off the field of play and I'm just looking at it going, "On your bike, mate", so I punch on and soon emerge at the ford town of Carrigaline. From this side, it's just council houses overlooking graveyards and a scaldy-ass set of units dating from the best-forgotten 80s. I cross the short bridge and slingshot out to Crookhaven where a series of marinae emerge round each elegant bend of the Owenabue Estuary before opening up into the majesty of Cork Harbour. On the far side of the water is the Soviet Republic of East Cork, with its fat chimney puffing goodo in the winter sun. **Mick Data, aka the sound Michael O'Leary, assures me that East Cork is no dissident republic. The rest of the county have been trying to get rid of them since God knows when but they refuse to Foxtrot Oscar.**

-   It's all very nice in Crookhaven. The boats looks deloosh in the sunshine, I find boat masts to be an unsightly mess, like having a windfarm squashed into your town. The centre is a small roundabout which takes in traffic from three hilly entrance-exits and one flat road that loops left along the sea. The businesses seems to be a mix of local pride and generic shite so I head straight for La Scala with its large colourful letterin \[LOOK UP\]

\
Sheil

Crookhaven

-   the exceedingly pleasant village of Crookhaven

-   Kobenhavn

-   Marina en route on entrance to the town, the river curving elegantly round (Carrigaline)

Sundays

-   shite day for travel writing

-   People finally have time for themselves so yapping to you is of no benefit to them. During the week they are in work and friendly chat is often a welcome break from the monotony of work.

-   

It has 30 hour jolly with eight hours of driving, six hours of cycling, five hours' kip, four hours' drinking and fock all faffing. A lot of people would be delighted with this result but I haven't soaked up enough of the characters, even though I've very much felt the character of the place.

-   even the return leg is a bit tight as I've to be home to collect my son from school at half-two

    -   this means I've a chance to revisit the greenway to Passage and scope out the post-industrial skronk along the Cork Marina

Carrigaline seems to be a working-class Brad Swiss full of council houses and units erected in the Spin 103.80s.

Belgooly (Pic)

-   the Irish for tonsils

Public Access

-   <http://www.indymedia.ie/article/77936?userlanguage=ga&save_prefs=true>

-   <https://struggle.ws/wsm/news/2002/kinsaleMARCH.html>
