---
title: "Wexford Outtakes"
---

research

-   eurovelo 3

-   norman way

-   burrows

-   A community centre with LIST MULTIPLE FACILITIES

**General Sitch**

The thought of cycling to several score more lighthouses on the side of the island has been overwhelming me, so yesterday I did a wordcount and I was just there looking at it, going, I can make a standalone book out of this. *To the lighthouse, part 1: The mild non-Atlantic way.* What remains is a manageable quantity of cycling, writing and mapmaking, which I can possibly dunzo this month before school's out and it's time for a summer skedj with the sprogs. Then I can worry Pat Rafterwards about the Wild Atlantic Doris and all those pesky islands and Northern dauntingly Ireland, maybe lash out a volume apiece for each of them. The idea only crystalized yesterday, so I had a look at the Freddy Forecast and decided to hit the Dermot today because the sun will be shining in the Sunny South East and there's blanket rain forecast for tomorra.

I've got a long day of it planned, picking up some outstanding lighthouses I've missed around the Wexford Coast. Lighthouse Pete noted that I missed the Duncannon lighthouses when me and Graham zipped past on our way to Hook Head. I also never saw Tuskar Rock from Rosslare Harbour when I was there so I'm gonna go and hunt for it. But this is really an excuse to check out the south-east Wexford coastline which I've missed. I want to know whether it merits being a part of the Wild Atlantic Way as County Waterford so clearly does.

**The lightbulb of shame**

Packing up last night took forever, between fixing punctures and a whole bunch of positive procrastination tasks like sorting out the guest bedroom for possibly Airbnbers, a slightly annoying set up that might save me from the horror of getting a job. I'm just off the back of an unrepeatable month of Metro Boulot Dodo up in Dzublin. Never again. So anyway, last night I didn't hit the hashtag til nearly midnight but I thankfully sleep until 6am and I'm in the Boola Bogger by 7. It's only like 65 Google minutes to Wexford, and I decide to spend the drive nursing the poor litle boy inside me who had to fend for himself in boarding school. I lash on *Automatic for the People*, as REM recently set me off, while in the juicer no less, and I only make it as far as Si*dewinder Sleeps Tonight* before it's all too much. Listening to Atlantic 252 in the car with my mam on the way home from school every Saturday afternoon. I've been listening to some lectures about shame and I'm both apalled and delighted to find out how much shame and negative opinion i have about myself. I've only been looking into it for a week now but the changes have already been massive because I can suddenly see now what I've been doing wrong. And doubly so as a parent. ADD EXAMPLES (OR MAYBE LET THEM EMERGE BELOW). Afterwards, I start listening to Tim Fletcher' - the same dude's - lectures about about complex trauma. I don't get any further than *the essential characteristic of complex trauma is an inability to relax*, and then I lash it off knowing there'll be plenty to relate to later. 

**Wexford**

I decide to approach Wexford from the Ferrybank side and have a gawk across the river at the lovely town slash future city whose atmos I love. Over the bridge, there's all day parking for a Lady Godiva but, instead of stumping up, I push on and piss away 45 minutes looking for free parking and worrying about having an easier arrival this evening when I'm smashed. Old habits, eh. I've 120k lined up so that could be 140k with tangents on top. That's as much as I've ever cycled in a day and almost the magical 100 miles aka 160.93km, a figure that's in my head on account of the athletics that's on at the moment. **Sharlene and Rhasidat running for more medals tonight. Ciara Mageean having slowly ascended to a championship gold. The accents are a whistlestop tour of the island. Rhasidat, from somewhere in Tallaght, has a fascinating mix of Old Dublin, where every second word ends in a /h/, and that aspirational Gen Zeeer intonation (which I need to learn how to understand and explain). *I just want to inspire the next generation just like others inspired me.* If you can't see it, you can't be it. I can't hear any of the grumpy Brochat I used to hear every day among the black teenagers in Blanch libro, where African influences have blended into West Dublin's emerging accents, allowing for the expression of a distinct social identity. Although maybe it just fades away after school when your localized curiosities get diluted out by the big bad world.**

I eventually park up in the Tesco Extra near the town then mosey in to the centre to take some videos along the quays. I go for coffee and a Barry in Cappuccino's Cafe on Main Street, where I hope to watch the world for a bit. A Dublin lady serves me and points me up to the Union. I hate doing my business in public because toilet paper is really just a substance for drying your Gordon after you've washed it, not a cleaning implement in its own right. Using it is like claiming you've mopped the kitchen floor after wiping it with a dry J-cloth. 

**James**

I stall it back outside and lash down a few notes before pottering across the road for a snap of St Iberius's church, outside which I try to rest my Paul van agin a wobbly bollard. A shabby shamanic figure, bearded and built like an ageing tighthead, winks at me and suggests I don't park it there. I explain I'm about to take a photo and he offers to take one of me and it and the church. He proffers some lowkey bigotry, wondering why I'm taking a photo of a Protestant Church. I tell him it all happened, whatever that means, and then he asks me if I'm from Dun Laoghaire. I tell him I'm actually from fockin Lucan and he suggests I keep that to myself, with my hundred thousand euro accent, a figure that is not far wrong, once you convert from old money. Being racked with shame about my #priviliged upbringing, I set about needlessly explaining myself, an onerous, humourless bit of bait I frequently take. Next time I'm just going to say that my aulwan was a lowkey snob who sent me to "a well-known North Kildare pratt factory that turns rich boggers into D4 dickheads", as The Slate so brutally put it back in the Caelan. After that my accent was mostly formed out of Trinners for winners and boozers for losers.

It turns out your man is a bit of a machine whisperer and he's telling me now about how the handlebars are too far forward on my bike and need to be raised. Too much pressure is on my shoulders not my lower back. He suggests I take the load off by arching my back a wee bit as I cycle. This explains the pains in my shoulders and why descending is so painful on this bike. Then he spots that the bearings on my back wheel are banjoed and he tells me to call him later if I need help. He also decides to send me the phone number for Ken the bike man who won't empty your wallet and I suggest we catch up for a Brit Award once I'm back in town later. 

Ken doesn't open til 10 and I'm anxious to bounce pronto, after all my faffing, so I just hit the proverbial and head out towards the Rosslares. I was disappointed to miss Rosslare Strand the last day so I jump off the N25 and head out **there, although Google Mops chucks a needless detour at me because it hates to see cyclists on an N road, even though it calls it the 'Three N25', a name I cannot understand until I start to see the number 3 on the EuroVelo signs that pepper the junctions along my coastal route. SEARCH AND EXPLAIN**

**Rosslare Strand**

The road to the strand runs dodges the Sloblands, a chunk of reclaimed farmland with no road across it, **and having returned to the N25,** I turn off at a roundabout for Rosslare Strand. There's a crossroads on arrival with a village to the left and the beach being just 100 yards in front, so I head there and admire the view upstrand towards the East Wexford Coast and downstrand to Rosslare Harbour where the scutty harbour lighthouse marks the outmost point. The beach is clean and sandy but littered with fist-sized rocks near the entrance point. Signs outline the long walk up the strand and back around. EXPLAIN BURROWS

**Videos**

I sit down and take some videos to talk about what's been going on so far today but I'm not happy with the format. I feellike more needs to be happening otherwise I just fill the gap with slightly rushed chat. Maybe I just need to practice and leave in some long Dan Carlin-y pauses while I gather thoughts.

There's an aulpair resting on a bench so I sit down nearby and start munching on my biscuits and cheese. I open with weather chat and it turns out the couple have driven down from Arklow today. I mention my beloved Hanging Rock beach but the husband tells me the cove is a better swimming spot as the water is more level. But they lament the loss of the North Beach which was washed away by Hurricane Charlie, and suddenly I can remember me and my sister Maggs looking out the window, petrified. That hurricane and HIV/Aids were the scariest things I remember from my halcyon early years before boarding school.

The husband talks about the proud history of Arklow industry, a pleasing contrast to what folk my age say about the town, 'which my da said will never come to anything'. Munitions factories in the '20s and locals moving to South Africa after. Hotels by the North Beach. Shipbuilding. He tells me "I'm a shipwright", as though he was heading back to the job after this little break. He tells me about laying the oak on an even keel and the Jim the supervisor coming to make sure the work was in order and afterwards he'd have to reset the wood to where it was. Angela, the wife, is laughing now, as if she's never heard the story in their fifty-odd years of marriage. I tell them nothing has changed. B**ut I'm just looking at him thinking, punters keeping other punters happy. Not my modus operandi.**

**\
We end up having a bit of coda chat about waste water issues and the lack of new housing in the town and he mentions being town foreman during the late Celtic Tiger, presumably before the town fell complete apart and I'm guessing it was his retirement age.**

\
I grab some UPF juice in the Centra and make my way up the village where the SuperValu TidyTowns people have interfaced nicely with the cash has clearly been pumped into the village. The businesses all look plush and **you don't get the sense of mutton dressed as lamb from an excess of hanging baskets.** Kelly's Hotel looks like a 1960's resort, with Palm Trees and a large well-kempt Fir Tree behind, a little piece of Med vibe which has leaked over to the

it is a Mediterranean Resort with Palm Trees and a sculpted Fir Tree. It seems that the Sixties Mediterranean Resort aesthetic has landed here, a wee bit of the continent that has leaked onto the land of endless winter.

A community centre with LIST MULTIPLE FACILITIES\
I mosey up the inner side of the burrow, beyond the end of the village, past some very nice holiday homes and then onto a tiny entrance at the end of the strand on the inner side of the expansive Wexford Bay. I'm delighted to see it from this side AND THE LAY OF THE LAND BEHIND. The water is Caribbean clear and a wee boat chillaxes in the shallow sea. I say hello to a few downandbackers out walking and I stop to look at a beautiful stone monument of the lifeboat that was used in like 1914 to rescue a wodge of Dano-Norwegian sailers on Tuskar Rock. Two ladies come, one a regular explaining the story to her clearly visiting friend. The regular is a classic of the genre, getting the most out of the summer season. Tank top, shades, no-nonsense short grey hair. Long walks in the morning. Vino of a presumably evening. I ask her about viewing Tuskar Rock and she tells me where to go in Rosslare Harbour and that there's a replica on a roundabout. It's a bit of a doublebackarooney but I can't miss it.\
It turns out that I did miss it because I turned off at Ashfield Roundabout where it sits, a needlessly tiny but beautiful replica of the real lighthouse. Clearly somebody's visions of a roundabout column was compromised and this fifteen-foot toy replica is only half visible behind the signposts, when real roundabout art ought to dominate the space like any good beacon.\
\
\
Exit strat\
Photo\
In a bygone day I could have taken the Ballinbola train home\
I can't leave the phone to charge somewhere because I need it to take a photo of the lighthouses, and then I'll need to charge it for five minutes after just to make it back using Ultra Battery mode. So I wander round the strand and take a snap of it from the strand. I'm lucky the tide is out a bit. I whip off my smelly gear, lob on my swimming jocks and run into to the ankle-high sea. I try to rinse myself quickly in the shallow water but  it's like being in a scabby bath that used to belong to your sister. My skin is encrusted with a long day's worth of crystallized salts. It's like I've been rolled around a giant packet of dioralyte and I doubly regret not getting my rinse on in Kilmore Quay. I'm raging because the water's not punishingly cold and I really wish I could lie back and start learning how to cool my jets in the water like a normal punter.\
I dress back up half-arsed because I have no towel and then I charge my phone in the shop yonder while soothing myself with a quick cup of Afternoon Tea, sitting on a low wall while watching chunflaz kicking a ball round the village's central junction. It's about 720 and i reckon I'll make it back to Wexford in two hours with wind on my back cancelling out the tiredness in my scramblers.\
ADD NOTES here\
The water is shallower than a scabby bath and I'm worrying about the time. I'm raging because the water is not punishingly cold and now I know the other reason why I can't just chill in the water. It's cos I can't relax. I'm going to have to legiterally  train myself to chill the beans.\
\
Calling James was a big step for me. Now admittedly, my options weren't great as the bus was gonzo already so I'd've had to thumb a lift from someone, but that's not the point. I knew from earlier that asking for helps was a live option and it was really great to have to safety net.\
A bizarre side effect is that I will now more likely keep on top of my bike maintenance because if I going to be asking people for help then I'll have to do my bit and limit the likelihood of my needing to ask them.\
Waiting for James is a welcome comedown from the brainfrazzling nature of cycling and I charge my units while drinking green actual tea. He rocks up in a van and steps out with a smile and no shoes. He spots a missing screw in my derailleur and reckons I'll need a newbie. Good excuse to bring the bike in and have its geometry rearranged too. He suggests I stall it back for a shower in his gaff and I offer to take us both out for food. We get down to a rapid-fire catch up of each other's backstory, the work he does with the homeless people of Wexford and the fact that he can't offer me a bed because there is already a homeless guy on his couch. Once he hears that I'm on the scratch myself he suggests we grab ingredients in a supermarket and cook it in his. So we park up by my Jammer outside Tesco, lob my banjoed Paul van into the boot and then wander inside to get ingredients. He wants to cook me his signature steak and french toast and I'm more than happy to oblige.\
and it turns out he moved to Wexford from South Africa when he was four  \
James shows up even quicker than expected\

It's nice to see this depth of attachment to a craft.

, **but clearly the job is even more deeply ingrained in his head than, say, me being a writer, which I struggle to identify with because i don't get paid for it and I'm too ashamed to just go for it**.
