---
title: "St John's Point, Donegal"
---

### **Spin 103.Yeats Country**

-   I have a deep love of word stress and have spent a chunk of my life studying it and teaching it. The passion theoretically extends to poetic verse but somehow, amidst my degrees in literature and linguistics, no one ever taught me about the hashtag rules of verse, bar my Latin teacher in secondary school. In the English-speaking world, the two subjects split apart and both of them crept up their respective Gordon in their own ways. Literature studies became obsessed with culture and all the subject matter that falls into the culture wars now. Everyone forgot that literature was about beauty of expression and havin' a giraffe. Meanwhile, linguistics focussed on speech only because writing was seen as too contrived, not really 'natural language', useful only for studying language in the past. Now you could record speech and analyse the bejaysus out of it. Of course, they threw the baby out with the bathwater, forgot about literature and, again, the inherent beauty of well-constructed language. Poetry wasn't part of the program and thus the patterns of poetry were completely forgotten about. And yet the study of speech eventually worked out how words are stressed and how metre acts across phrases. The end result is that the two fields of study are ready to overlap but, when I moved out of academia, it hadn't yet been done.

    -   metre within words and across phrases

    -   known as Pottie because he was a bit of a space cadet

-   You didn't study poetry so you didn't need to study the patterns inside the poetry. Hence no study of verse.

-   People eventually began to care about stress in words and phrases but they

-   ve always wanted to visualized

## **Fundoran**

-   The coast of Leitrim feeds into the outskirts of Bundoran and it's a relief to be back in a large settlement, especially this one which has been optimized for holiday-making, with

    -   wI follow the road straight to the main beach which is very close to the town centre. In

    -   I head straight to the beach in Bundoran. It's a really

-   The tide is out but a huge knee-high pool survives and it's the perfect spot for a bathe and a blether. As I'm getting dressed, a dog is running and barker too close to an increasingly frightened lady and she's trying to tell the owner to put him on a leash, but yer man is being all *what are you on about?* I mosey over in case it kicks off but the dog finds something else to bark at and I get yapping to her. She's more than happy to give me a quick blast of her life story, or at least the story of her love life, working backwards from this trip.

-   She turns out to be a Cyavan Gyal and, fittingly, she gives me an exact breakdown of the price of her little holiday here. The hostel, of all places, was only fifty euro. A private room. But she called her friend from Sligo to go halves on the craic, so they only paid seventy between them for the room, a double and a single bed. Breakfast included too. Not a fry up, mind, but toast and coffee and fruit. I told her it's a barg, the cheapest room in Ireland, and she said the dinner in the pub was eighteen euro and that was enough for her, with a full plate of veg and potatoes and lovely meat. With the two gin and tonics – that's enough for her – the whole trip barely came to a hundred euro, as the bus was free now that she's over the magic age.

### **Sure we all partied**

-   She had cancer in the early 2000s and got over it but she's never worked since. Hated it. Used to work in a factory before that and couldn't go back. So she moved to Malta to get better and she could do because they just put your disability payment in your bank account. That was the Celtic Tiger all over. I remember it well myself. Everybody had a piece of the pie back then, and the mood was great. Every summer in my dad's shop the customers would have more and more cash and load up their vans with animal feed before jetting off to the sun. This was an era when college students got twenty quid an hour to hand out free booze.

-   Then in the 2007, I was twenty-three and doing a 'six-month' maternity cover in Alexandra College, teaching maths. It was from April to December, and the six months didn't include good ol' June, July and August, so I went on tour around Europe, mostly festival hopping, with my Morocc'n'roll money being sent straight to my bank account. The only catch was that I had to come home once a month to sign on, so I had to keep within Ryanair's ambit. I did two weeks of island hopping in Croatia, a week in Sarajevo, home for a bit, off to Benicassim for a week, a festival so intense that our tag line was *We're not here to have fun*. About twenty of us went to the Sziget festival in Hungary for a week and I finished up at the Edinburgh festival, drinking Turbo Shandies to squeeze out the last of my party energy.

-   I still have and use the same rucksack, with The Brendan Voyage written on it, along with the names of the countries I visited, in their own language of course. *España, Hrvatska*, *Magyayorszag*. It was tough getting back to the algebra after that.

-   People often remember the Celtic Tiger as a ridonculous era where taxi drivers would own three properties, including one in Bulgaria. But beyond the scarlifying opulence and excess, there was a basic quality of living for a lot more people. Students went to college for almost nothing and could fend for themselves, minus the maybe rent. Grown-ups could buy a home and plan a family. Ageing parents didn't have to house their grown up children who could go out and live a little. I don't know if elderly people's lives have changed that much although I wouldn't be surprised if more of them do full-time childcare now for their grandkids.

-   We've lost so much of that

-   Sometimes we think of the Celtic Tiger era as something unreal and, in many ways it was, but the truth is that it was the only period in Irish history when most people were materially comfortable and could really enjoy their lives. It's tragic that we've moved into an era now where

-   Maybe it was just a better time because phones allowed us to stay connected to people but not connected to the Jimi Internet.
