---
title: "Charles Fort & Galley Head"
---

**0838, Thursday, April 10, 2025.**

To do

-   Notes transfer

-   audio notes

    -   write up, ASR possibly

-   Geography explained at the edges

------------------------------------------------------------------------

I’ve been sidelined for months and I only got back on my Dick van a fortnight ago. The reasons are equal parts worrying and scarlifying. Now, I’ve had a bucketdermot of injuries in my time – we’re talking head, shoulders, knees and toes, and eyes and ears and mouth and nose. But usually something injurious has to happen. A twisted ankle, a knee in the face, a missed volley. GK once dropped a wardrobe on my big toe and it was the sorest of them all. Proper puke pain. He was buying it on DoneDeal and we mistimed the lift. Minutes later I’m resting on the floor of some Jean Claude’s sitting room, with a bag of iced peas compressed onto my foot and my leg elevated on the couch.

This time, however, I did nothing. And that’s the problem. Years of sitting on my Dexter Gordon has caused my upper body to degenerate into a useless set of

After several years of sitting on my Dexter Gordon, my upper body has degenerated  

ended up with rotator cuff tendinopathy

 thanks to a life of playing in all of the madzer positions (hooker, flanker, wicketkeeper, defensive midfielder)

ago so there have been no lighthouse trips since December

**PART  2. The wild Atlantic Doris**

10^th^ April, 2025

I haven’t cycled to any lighthouses for months because I’ve been sidelined with a shoulder injury and I only got back on my Dick van a fortnight ago. The reasons are both scarlifying and worrying, as my injury was not like any I’ve had before.

-   I’ve had a bucketdermot of injuries in my time – we’re talking head, shoulders, knees and toes, and eyes and ears and mouth and nose. But usually something injurious has to happen. A twisted ankle, a knee in the face, a fresh air volley.

-   One time, GK dropped a wardrobe on my big toe and it was the sorest injury of all. Proper puke pain. He was buying it off DoneDeal and I came along to load it in his van. But we mistimed the lift and minutes later I’m resting on the floor of some Jean Claude’s sitting room, my leg elevated onto a couch and a pack of frozen peas on my pulsating toe.

-   This time, however, I did nothing in particular to get injured. And that’s the problem. Years of sitting on my Dexter Gordon has caused my upper body to degenerate into a bundle of flaccid flesh incapable of making any sustained efforts. Pushing a pram has been causing me severe pain. One day I had to drive for three or four hours and I was fierce stiff Pat Rafter. A night or two later I woke up in screaming pain, incapable of finding a comfortable resting position. Even a sling was little use in supporting the weight of my arm. Two days later I was in the kitchen, cooking Christmas dinner with one hand while my wife was in bed with Craig David**, and obviously we couldn’t join my family for the day and spread the virus**. I went to the Loughlinstown injury clinic and the doctor diagnosed me with rotator cuff tendinopathy. He told me the hospital physio would be in touch, but their wires got crossed and it was six weeks before I got a bastid appointment. By then the pain had dissipated enough that your wan discharged me after a solitary online appointment, as my pain wasn’t severe enough. But I still couldn’t push a pram, drive a car with two hands or write on a blackboard, my main activities in life, nor could I cycle a bike. Eventually my left arm flared up, having had to bear all the excess weight, and so I called Andy Watson, my physio slash saviour who always fixes my issues in a single, often agonising, session. His competence comes with a backlog, so I lost another month of waiting, followed by two more weeks of training the arm. In reality, that involved me standing around playgrounds or the school yard, yanking rubber straps in repetitive motions while I supervised the next generation’s playtime.

                So here I am now, back on the road

After several years of sitting on my Dexter Gordon, my upper body has degenerated 

ended up with rotator cuff tendinopathy

 thanks to a life of playing in all of the madzer positions (hooker, flanker, wicketkeeper, defensive midfielder)

ago so there have been no lighthouse trips since December

------------------------------------------------------------------------

<https://www.strava.com/activities/14139284526>

*School's out and the weather's deloosh. The sun has been blistering for donkeys, the longest patch anyone can remember in April. The calm mild air is warmer in the mind than on the flesh, making it perfect for the Paul van. Yet for now I've got gloves on and I'm thinking of lashing on a second jacket as it's Baltic in the shade and will be till the terracotta oven below warms up the overnight air.*

*I've just plonked the jammer in Innishannon, a junction village beyond Cork City that will allow me to do a clean looparoo over two days. I'm now cycling along the steep bank of the River Bandon which I'll follow in to Kinsale and thence up to the Charles Fort lighthouse which I didn't have time for the last day. After that, I'll head west for Galley Head, hugging the coast as much as my freshly unfit legs let me. I found a cheapo bed in Leap, 20k beyond and that extra chunkeen means I'll probably have to skip the Seven Heads peninsula. Tomorrow should be a handy one though, heading to Skibbereen and Baltimore where I'll get a short ferry to Sherkin Island. I'll get the hopefully boola bus back from Skibb, before scooting home for family duties over the weekend. But I put little faith in Bog Eireann and might have to punch in an extra sixty-eight kilometres along the main road. Say your prayers for me, yeah?*

Structure

--\> spiel about life, taeching, injury

--\> road to Kinsale

-   local businesses,

    -   Lillies pharmaceuticals, brewery & distillery, sponsoring local events.

        -   actually looked at a job there doing voice assistant work for lab workers or docs. someone for them to yap to all day

        -   several peeps out jogging one with Lillies name on it, 10k run advertising

-   hack of Kinsale, can't put my finger on what i dont' like about it

    -   aulflas sitting on a bench, out of place

    -   a curiosity about Cork is that you see the boggeriest of boggers, unintelligible aulflas

        -   sitting by the ¿library

            -   Cork County is full of human relics whose dress, manner and accent makes them...

            -   people complain about immigrants taking over but the real problem is younger people

        -   in amongst the ageing hippies, English dropouts, ladies who lunch, general english people

            -   half of the accents i´ve heard today, including Stewart Lee's nan etc

            -   English people who have long since identified their country as a Brad Swiss

-   Charles Fort

    -   waiting, scottish fella

    -   Yuge

    -   Burnt down, previously loved

    -   Reasonable price but shite. Self-guided bollocks

        -   colosseum-like in its emptiness. Forum-esque

            -   the size of the plae makes it feel extra desolate and probably I'm just lonely

                -   need someone to bring this place to life. Self

                    -   cf Joyce and Rome selling the bones of their granny to the public

                -   one chap is getting a tour.

    -   

        -   Sure I know nothing of the place now, a collection of burnt out buildings, a fortress of the Lickety Splits, burnt by the Anti-Treaty forces during the Civil War

    -   William Butler

        -   Lighthouse: original was on a height, like in Wicklow Head

        -   new jobbie needs a lick of paint

    -   lads working there, tired look of state workers who have spent too long not near their ceiling, not being challenged

        -   I'd wanna be careful of that as a teacher, havent written in the last four months, serious lack of ceiling action, al

        -   these are worn out, bedraggled men, deressed like continental waiters with no tables to serve, dodging work when it comes their way.

    -   Cafe:

        -   if you buy a bun, you can park your bum. Should be Buy a bun, park your bum.

        -   I didn't have a big breakfast – for once – and they have no more than a sausage roll

    -   History of the place

    -   can't access lighthouse – feed

        -   fella comes back with his passive aggressive jibe of you didn't get to see it did you (not my job, youll have to scarlify yourself with someone else)

    -   Food, cafe, bored barista, doesn't bring food out

        -   seat for bum yet paid in already, big issues in the rain slash wet ground

    -   Rome, showing off bones of dead granny.

-   Exit Kinsale

    -   back roads to Timoleague & Ballinspittle.

-   and hopefully I'll get the boola bus back here from Skibb

-   cycling towards the Charles Fort lighthouse in Kinsale which I didn't have time for the last day. Right now I'm climbing up the river bank of the River Bandon, heading towards Kinsale where I'll visit the Charles Fort Lighthouse which I didn't have time for the last day.

-   I've a curious allergy to Kinsale

-   Spanish seaside homes, sharp square balconies, brilliant white with dark grey trimmings, a colour scheme fit for a faceless corporation.

<!-- -->

-   

<!-- -->

-   cycling up onto the bank of River Bandon, heading fro, Innishannon to Kinsale

    -   hedges details!

-   with easy access to Kinsale, where I will visit Charles Fort lighthouse this morning, and Baltimore in West Cork, where I'll head out to Sherkin Island lighthouse tomorrow morning. I'll hug the coast, inasmuch as I can, and take in Galley Head this afternevening.

-   West Cork and, to the south, Kinsale where I am heading first.

-   that splits to West Cork in oneKinsale to the south.

-   I've been back teaching maths in a tiny private secondary school with no stress and the

-   It's a stress free existence, bar the odd headstrong Spaniard, but the money is gack and I won't survive long at it. Plus it's just not enough of an intemellectual challenge.

-   But I do love being with people

------------------------------------------------------------------------

### Kinsale - Timoleague

-   brown square fields like a dry foreign country

-   this is belgium

-   brown road,

-   recording voice find some mental energy

    -   Radiomade world record, digging deep into the chat you have

    -   seldom do people need to go that far

-   aulfla with dog gives me directions, inasmuch as he knows himself In his eighties. Jumper nearly as old, holes in it, bit of rope used as a lead, punchonthrough,

-   fells pulls up in a fukov jeep wondering if he can drive through= and he warns me its a fuckup up the way. he´s fucked off with the roadworks and (lack of) signposts. I tell him he's grand to drive trhough

-   when I get there, there´s an easygoing tall fella, grey-haired and unperturbed by the seeming chaos caused by the work he is engaged in

### **Ballinspittle**

-   Virgin Mary apparition
-   McCarthy´s Bar?
    -   1985 revisited written 2025
        -   <https://www.irishexaminer.com/news/spotlight/arid-41546248.html>

**Timoleague**

-   long, inland estuary, run-in to Timoleague and I´m thinkin that this is very typical of the south coast of ireland. An old silted estuary and I bet a Norman cASTLE UP THE WAY. oF COURse it´s timoleague abbey wjhoich is a trail and the churches are garjus too.

-   As I approach Timoleague I realise it's going to be one of those silted estuary towns **whose heyday predates Shakespeare**. In fact it was the Bard's contemporaries who burnt out the abbey in YEAR\

    -   There's a yuge monastery in ruins right on the ESTUARY name

    -   i´m tired now making shit decistions. thank fock for a quick Brit Award

-   There's nowhere proper to eat in Timoleague, until Charlie Maddens opens for lunch tomorrow, so the benches outside Centra will have to do me, says a friendly aulwan out watering her hanging baskets. It turns out to be a blessing in the skies as I grab a quick blast of life among the lower orders in the community – kids, alcos, resting labourers, budget cyclists and the odd motorist coming up for air.

    -   

-   Two touring cyclists are settling down to lunch and auf Deutsch spraffin. I can't pin down their jacker but they seem to be in a hashtag getting to know you phase and have little interest in expanding their micro-network. But I'm jacked and glad of human presence. Yerwan is a *young thin pale soft shy slim slip of a thing*, dressed in an unlikely woolly jumper from her grandad's possibly attic, while Bro is a *heavy trudging lurching lieabroad*, with hips the size of a cattle farmerette's, shrinkwrapped in Lycra, and his ensemble concertinas in and out with every puff of his rollie. Both of them have heavyweight urban bikes and look like they were cycling 3k to work one day when a notion overcame them. It's nice to see punters innit for the bantz and not the flecky, mortifyingly expensive Richard Gere.

-   I'm trying to slip in to something more comfortable but it turns out one of my runners has bounced out of my overfull and thus unsealed backpack. As has my nice cycling jacket, my long johns and my water bottle. I believe the community use the term *ADHD tax*. God only knows where I can pick up cheapo runners by end of business in this corner of the country. Else I'll be out for dinner tonight in a pair of old, scratchy cycling shoes. I walk into the shop in my socks, knowing I need to hashtag get the protes in but I can't convince the lad at the deli to load me up goodo. The stingy prick grabs a big handful of thinly sliced egg and neatly places them along my roll before returning the remainder to the stockpile. I'm not sure if I should call the hygiene police or scold the manager.

-   The warm lady at the counter suggests I grab a basket to help me carry my many items: a skimpy baguette, a brown scone for some reason, a pear, a flavourless americahnay, a tiny OJ for the Doolittle, two litres of uisce and a birra Moretti. I plonk my basket on a picnic bench, not too near ze Germanz but not too far, and beside me is a frail, grey-haired grey-skinned smoker, old before his time, drooped over his rollator.

-   I realise my body is craving salt, as is my food, so I stall it back in for Tayto nutrition to yer wan's hilarity. On my return, a crow is trying and failing to yoink my entire baguette and my Germanophone counterparts are fending it off. It's a chance at solidarity and I manage to elicit their respective journeys off them – he's cycled here from Rosslare and she may or may not do the entire Wild Atlantic Doris – but his wide back and broad buttocks are protecting his prey so I leave them at it.

-   A big strong workman from Eastern Yoorope sits down with a mahoosive ice cream and, given the lack of ostensible emotion on his face, I feel morto for him until his even larger colleague, bald and paintspeckled, ambles over with a big-ass 99 and my emotions recombobulate as their mutual scarlification resolves into a lovely little moment. The lads lick away in harmony and are soon delighted to ogle some jailbait as her hungry bum catwalks past.

-   Next up is a procession of uniformed primary school boys, aged like ten or eleven, also here for ice creams. The aulwan teacher sits them down at the low wall afar and the lads march shopward in sixes with the youngwan teacher, dressed in woke uniform: short militaryesque jacket, rainbow lanyard and stonewashed jeans pulled up to her thruppeny bits but down only to her calves.

-   I start getting ready to face the road again, as do the other cyclists, when a sound normal curious local man starts interviewing them about their journeys. Allofasudden an aul codger comes up to me and shoves a handful of coins into my hand, orderasking me to get him a big bottle of cider inside. I oblige of course, remembering heroic teenage days when we'd drink naggins and flagons in fields after convincing grownups to purchase them for us. I come back and find him on the low wall afar and he shakes my hand and tells me he's after getting seven stables to clean out. Cash for cans it seems. He pounds out his life story in about four sentences. Martin McSomething. An alcoholic who worked all over the country in a some line of unintelligible work. The fifth youngest of twenty-one children. His birthday is next week and I have to promise to come. There'll be cans and whiskey and vodka. He'll be sixty-two and looks eighty-five about the Brendan, but it's like talking to my booze-enthused teenage self and it's time to disengage.

    -   I'm reminded of Mad Ken Kelly, the Irish tramp in London who may have killed a dozen or more people. Of course

-   The interruption has saved me from having to be invited – or not – to cycle onwards with the other pair. Before I bounce, I get one final performance as Martin scuttles over to the tall petrol price sign and whips out his comically large Mickey before unloading a worthless dribble and gets yelled at by a nearby driver. He scampers back to his surprisingly bicycle and skidaddles off.

-   The normal local fella comes over and mansplains Martin's jacker. He also wants me to follow the coast road, but I know my legs won't have the extra twenty clicks in them later. I'm jacked after forty-five and I'm only halfway there, and weighed down further by my overnight bag. The Seven Heads are on the Eurovelo route but not the Wild Atlantic and I suspect locals have to nearly petition tourists onto their peninsula. In his gorgeous book, *Cycling in Ireland*, David Flanagan recommends them. I

-   as David Flanagan suggests in his

-   

-   But I cycle along the top of the peninsula, twelve dull cattlefarm kilometres to the old market town of Clonakilty.

### Clonakilty

-   I cycle along the top of the Seven Heads peninsula, twelve dull cattlefarm kilometres and arrive in the old market town of Clonakilty. The main st reminds me of Wexford Main St, small shops, interesting, crafts etc, no humour for checking them out but, head is melted, wouldn´t be able to read now

-   Coffee – Barry –

    -   shoes, dealz

    -   yer wan will sort ya out

    -   do you want her number

-   I don't know what i want in Clonakilty other than to have a gawk at the gaff and I'm excited to see that it's bigger than I had imagined, with its entrance point being dominated by a Seeper Volye and small hashtag retail park. I doubt it's big enough for a TK Maxx, my proxy metric for a self-sufficient town, although the main street does remind me of Wexford Town, long, narrow, atmospheric & full of artisinal or at least independent shops. I gawk at a bike mechanic out fixing bikes on the path and pull in for a yellow in a nice smelling cafe. There's no union but she sends me to their ?sister cafe in the square up a bit – literally 50 metres – where tables and people sit out in the sunshine BANG OF BORDEAUX MINUS PEOPLE DRINKING ACTUAL WINE DESPITE HEADING OF SHOP. Being Irish and unused to organzied banter, the seats are orkwordly arrange in restaurant formation so the place brings that horrid indoor tension outside. These places, and indeed their customers, need to recognise that chilllaxobant doesn's occur betwong people sitting opposiont one another. You need to be watching the same TV

    -   watch what happens when you let customers pull out the tables themselves and see how they congregate, each of them finding their own space yet not too far awaya nd thus adding atmost CAFE in MALAYSIA and pre-barricade Grogans.

    -   Anyway I get back to the cafe, have an outstanding macchiato and a customer tells me I can buy runners in Dealz which I do for fifteen nicker, being served by a socially awkwards Pontiac man with long red hair and rainbow coloured nails. It's endearing to see such colour on a grown man but he reminds me of child whose only form of self-expression is through pictures rather than an ability top express himself with words.

-          **Hang around and stuff just happens**

-          **This kind of stuff never happens in bastid restaurants where everyone clumps alone, pretending no one else is there**

Galley Head

-   *Thankfully, on this occasion of joy, there is no need for me to witness any modern forms of compassionate discipline. I was almost subjected to it myself in work last week. I had to kick out a student for insolence and I reported it up. Instead of them just putting her straight, they wanted to arrange a supervised meeting between me and the student, as if we were both guilty. Out of instinct I agreed and then spent a sleepless night bricking it. I mentioned it to my colleague in the morning and he said it's too humiliating and I realised he was right.*

------------------------------------------------------------------------

**Wednesday evening.**

-   School's out and the weather is good. It's been blistering for donkeys, the longest patch anyone can remember in April, and perfect for cycling with calm mild air that is warmer in the mind than on the flesh.

-   I tell Sharifa I'm hitting the road and she's pissed off to be looking after kids on her week off when she's supposed to be relaxing slash looking for a new job. But in squareness next week I'll be off work and looking after kids myself, all week

-   N25 – driving in to the sunset again, But the west might be a lot like this with magnooficent sunsets (like in Bantry slash Ballylickey)

-   I'm gonna miss Cork City and my little journeynees around the county. *Of course I can still come again lol* but it's a particularly good spot

    -   been using it as a base and it's a habit worth adopting. CHECK LIST OF HUBS (e.g. Donegal Town (yawn)

-   

-   I drive to Cork, kip in Sheila's again. My first destination is Charles Fort in Kinsale, then Galley Head a couple of peninsulas over and then Sherkin Island off Baltimore in proper West Cork. If I can, I'll get to Fastnet but that's a big one and merits its own day out.

-   I really ought to get out to Fastnet while I'm in the area but the tours don't start until Saturday. Now I could have times my trip to be here on Saturday but I don't trust the weather and I don't have the patience. Plus it's not good to squeeze in too much, like and American tourist. Likely I'll just come back

    -   Geography of West Cork, the need for a boat to get the most of it

        -   Undercutting below so no permission to go down

        -   The lads are dressed like waiters with no tables to server

-   and park the car in Innishannon this time, a junction village that connects West Cork with Kinsale to the south.

**People**

I wasn't in the Emer for Kinsale the last time, being tired, thirsty, hungry, struggling for daylight and stressed out about getting my bike out of there.

I feel lowkey bad that I'm still not interested.

It's rush hour in the drivethrough village of Innishannon. I've parked here so I can easily hit up Charles Fort Lighthouse in Kinsale (20k) then make my way west

GK is lowkey thinking of

**Innishannon**

-   kids, athletic vibe, the gear, the hurleys, the bus,

    -   bang of sports off the kids between the trackie Bs and hurleys on their way to school. They are wearing shorts and I´m thinking of putting on a second coat.

-   not the kind of people who I should ask about loading a bike onto a bog eireann bus

Aulflas

-   i'm not sure if there's more aulflas in West Cork than in other rural parts of the country but they stand out more here because they are so starkly different from the most of the people.

    -   people think it's the immigrants eroding the culture but it'sm mostly just the young people.

    -   people love to blame immigrants for coming over here and ruining the place. But the real threat is younger people EXPLAIN

        -   I once asked my dad how it feels to live in a world where everyone and everything are different from the world he grew up in. He didn't quite grasp the idea but it must be a lonely place and nowhere

        -   Maybe it's just the fact that aulflas round here have kept up the habit of loitering. Sitting on benches and walls waiting for the bantersmash. Talking weather and cattle and racehorses.

-   Demographics of Cork

    -   some stack of English accents. Could well be on holidays in Spin

    -   Hippies, random lad in Kinsale sounds like Stewart Lee's nan.

        -   In a county full of boggers,

    -   

-   I was there, *naked on a beach in Ibiza*, BUT WHAT WAS I THINKING ABOUT

**Charles Fort**

-   Dour Scot over in Kinsale visiting his aunt

-   reimagining the life of the soldiers based on the names of hte buildings.

**OPW workers**

**Iron Curtain dodgers eating ice creams**

**Twenty kids on the ball eating ice creams, with their teacher decked out in woke uniform (jeans, no ankles, short pseudo-military jacket**

**German Cyclists**

**Fella on the wall yapping,**

-          Quizzing us

-          Tells me about Martin

-          Wants me to follow the coast road and I would only I know I wont'have the legs later and I'm gutted

-          His poor peninsula didn't get the nod from the Wild Atlantic way so they locals probably have to use guerrilla tactics to recruit tourists, hounding us with niceness and yap

**Timoleague**

-   There's nowhere proper to eat in Timoleague bar the benches outside Centra but it turns out to be a blessing in the skies as I grab a quick blast of life among the lower orders in the community – kids, alcos, resting labourers, budget cyclists and the odd driver coming up for air.

**Alco in Timoleague**

-          He asks me if I’ll go and buy him a big bottle of cider and hands me  glut of coins. I’m thinking they might have those old 4 pint flaggons we used to buy as teenagers or, as with this poor man, ask people to buy for us in shops.

-          I grab him a big cold Bulmers bottle and hand him his change. He shakes my hand and tells me he’s after getting seven stables to clean out. He’s not into horses, it’s just a bit of work to keep the show on the road. He tells me the line of work he’s done all his life but I can’t understand a word. It must've been something awful complex. He did it all over the country. He tells me he’ll be 62 on the 18^th^ of April and invites me to his party. There’ll be cans and whiskey and vodka. A man like that might struggle to pull together a large gathering but he's the fifth youngest of twenty-one children so there might yet be a few around to celebrate

-          He’s been an awful alcoholic all his life

-          **Hang around and stuff just happens**

-          **This kind of stuff never happens in bastid restaurants where everyone clumps alone, pretending no one else is there**

Galley Head

-   71 year old lady who has lived there all her life. Never seen anything bad happen.

-   Open valley of reeds, beautiful width of space bounded by midsized riverbed, opening onto the beach

-   The landscape has changed over her life, There used to be a tunnel of water they'd play in but it's all been washed away

Ger Airbnb

-          Interesting to get a guest's view of a ramshackle Airbnb option

Bnb slash café lady

-          No hello or welcome or any pretence towards that or even like a gesture or nod in the direction of concern. Hasty departure

Boatman Ciaran

Sherkin Resident slash holidaymakerf

Chris & Rose & Kids

Pints in Bushe’s

**Chris Murphy O'Connor**

Chris is like *I'll see you in ten years on your next visit* but I tell him I'll be back to see the Fastnet soon and he says he'll bring me out. And to bring GK. I'm over the moon. This is exactly what I want. Connections in the boat world

I ask him how much a boat like that costs and he's maybe ten grand. Although the good new ones are forty. Basically the price of car. You might even get cheaper ones.

-   I don't actually know Chris very well, other than a handful of sessions ten to fifteen years ago, although he's good mates with Jasper and GK

-   He's like do you remember Rose and, being shite with faces, I don't at firstuntilç I hear her voice and it comes back to me.

-   The long tough winters are heavy going for a family

------------------------------------------------------------------------

**Leap AM:**

-   I'm up at like half seven and don't know what to be doing with myself. Do I just hit the Dermot and squeeze in as much as possible or do I look after myself?

    -   This is literally the first time I've been in the situation.

    -   So I mosey up to Centra in the petrol station slash catholic church end of the village and sit down in one of those hallelujah corners where you can eat in peace without

    -   I still end up spending seventeen nicker on fuel, between my five euro breakfast roll, coffee, two litres of water, and two bags of scran for the road (salted cashews and chocolate raisins)

My bike is parked near the bus stop and the presence of some Yanks tells me there's a bus coming soon. I ask the driver whether I can stick my bike on later and he tells me it depends on what kind of vehicle is coming. The VB buses don't take bikes but these ones do. You can track it on *bustimes.org*. Gotta love that kinda thing. I bet there's busspotters out there, sat in their bedroom, tracking these vehicles and posting on forums about which

------------------------------------------------------------------------

The ferry to Sherkin Island is at 1030 so it's a bit of a panic getting there but my legs are strong at this hour so I drill it on the N21, scuttle through Skibbereen and leg it out to Baltimore. With a tiny bit of planning I could have had a quick look at the rowing club that has produced four Olympic medal winners ADD VIDEO OF O'DONOVAN BROTHERS INTERVIEW

-   I pass the bus stop and nip in to Dave Long's travel agency where the girl assure me me I can lob my bike on the bus later. It's a big relief cos those new Bus Eireann buses take fock all luggage

    -   good chance for a rant here:

    ```         
    -   prams, bikes, hot food, the lot

    -   no jacks either
    ```

-   The ferry is cash only so I ask the boatman if I can jump on and pay later cos I'm in a bit of a rush. He's sound about it and tells me to get cashback from the Gala shop opposite. He gives me a lift down to the TYPE OF BOAT, where a dozen tourists sit, low intensity types whose idea of a day out begins at 1030am.

-   There's a LONG CHURCH RUIN at the tiny harbour, and then a very steep ascent out. Twenty peddle strokes later I'm out of breath and turning away from the crowd towards

-   ADD MAP

-   <https://www.sherkinmarine.ie/island.htm>

-   <http://www.irishislands.info/roaring.html>\
    Sherkin island has the sort of complex shape that could never be imagined by a novelist COMPARE WESTEROS AND THE GENIUS OF STEALING EXISTING ISLAND SHAPES. I was hoping this'd be a sheep's island but suddenly I'm literally in the middle of another blasted cattle farm and struggling to find my way. I follow the only visible road and it's made of grass. Not a road with grass down the middle of it; but ten feet of primo Irish verdure that is kept from the cattle, like a neverending cricket wicket only with a lazy groundsman.

-   

-   çIt leads a few houses looking across Horseshoe Harbour which does exactly what is says on the tin. CF CHRIS PLONKING ANCHOR AND SWIMMING. I double back, faff about and dilly dally for donkeys. I even take the chance to call my wife and say hello. I hear noise in the shed but it's the cows who, despite their mellow nature, seldom prove to be good tour guides. Eventually I just hop the boola gate and trudge across the roughest terrain that I imagine cattle being able to manage, in my non-expert, farm-adjacent-at-best opinion. TRACTOR TRACKS AND CATTLE-BATTERED GROUND

-   I yomp on and soon approach the lighthouse from the precipitous side and I decide against climbing up to it with a massive drop below. I soon find a precious lick of clean grass and a skinny steep curving trail up to the lighthouse. It's times like these that you really appreciate the REGIMENTED work of CIL or the old BALLAST BOARD with their practice of putting in mini-Roman roads in these most isolated of places.

    The lighthouse campus is tiny, SIZE?, *a notable historical architectural ensemble*, REFER with a cleanly boarded up house fit for one and a strange cast-iron lighthouse standing out the back like an introductory dildo on a bedside locker. It reminds of the time I drunkenly kipped in Mark the Ginger Protestant's bed and, trying to reach for my phone in the morning, I grabbed his new girlfriend's toy.

-   The lighthouse lacks the girth of a stone lighthouse which are always heftier up close than you might imagine**, as we've discussed before**. The building material perhaps marks the beginning of the end of the great lighthouses, where beneficent functionality required strength and heft to fend off the elements experienced in places like this. Not far from here is a place calledRoaringwater Bay.

-   Nowadays, we've got two lights in Greystones Port, as skinny as a bus stop and as faceless as a techno DJ, squirting green and red light into the night.

-   Similarly, we have seen that same trend having occurred in modern man as our physiques have dwindled into dweebs

    -   Gone are the muscular workmen of yore, their bodies toned from countless hours of toil, (SHITE WORDING) being the subject matter of Lady **and the excitement of their resultant, inherent sexuality**Chatterley's lover, DH Lawrence's banned novel which dealt,

    -   Presumably (CHECK) Lord Chatterley

    -   The counterattack has long since emerged

    -   now is that we get the vain pastiche of boys with beach muscles, sculpted in a gymanasium according to a prescribed regime. And women now too, understandably scared of sprouting a formless UPF-bum, are squatting themselves into

    -   Gone are the days when yound ladies were happy to look like "bus stops with mascara"

-   I've even lived throught his transition myself, having spent large parts of my youth handballing giant bags of animal feed, a job that toned me into a functional front rower with no need for a gymnasium to sculpt myself into the necessary body shape. And now, here I am, doing sad-ass exercises in order to prevent my shapeless arms from degenerating into total dysfunction

-   BUILDING MATERIAL which as we discussed

Roaring water journalñ

<https://roaringwaterjournal.com/category/roaringwater-bay/>

-   Before I head off for more cattle fields

-   He tells me he's an alcoholic and he

-   It's a tragic state to be in, labouring at 62 for

-   I'm reminded of Mad Ken Kelly, the Irish tramp in London who may have killed a dozen or more people. Of course

-    and we all do a chunk of chat apiece with a sound normal curious local man

-          I grab him a big cold Bulmers bottle and hand him his change. He shakes my hand and tells me he’s after getting seven stables to clean out. He’s not into horses, it’s just a bit of work to keep the show on the road. He tells me the line of work he’s done all his life but I can’t understand a word. It must've been something awful complex. He did it all over the country. He tells me he’ll be 62 on the 18^th^ of April and invites me to his party. There’ll be cans and whiskey and vodka. A man like that might struggle to pull together a large gathering but he's the fifth youngest of twenty-one children so there might yet be a few around to celebrate

-          He’s been an awful alcoholic all his life

-          **Hang around and stuff just happens**

-          **This kind of stuff never happens in bastid restaurants where everyone clumps alone, pretending no one else is there**

Galley Head

-   we'd get grown ups to buy us a f

**Alco in Timoleague**

-          He asks me if I’ll go and buy him a big bottle of cider and hands me  glut of coins. I’m thinking they might have those old 4 pint flaggons we used to buy as teenagers or, as with this poor man, ask people to buy for us in shops.

-          I grab him a big cold Bulmers bottle and hand him his change. He shakes my hand and tells me he’s after getting seven stables to clean out. He’s not into horses, it’s just a bit of work to keep the show on the road. He tells me the line of work he’s done all his life but I can’t understand a word. It must've been something awful complex. He did it all over the country. He tells me he’ll be 62 on the 18^th^ of April and invites me to his party. There’ll be cans and whiskey and vodka. A man like that might struggle to pull together a large gathering but he's the fifth youngest of twenty-one children so there might yet be a few around to celebrate

-          He’s been an awful alcoholic all his life

-   

-   Before I head off for more cattle fields

-   He tells me he's an alcoholic and he

-   It's a tragic state to be in, labouring at 62 for

-   I'm reminded of Mad Ken Kelly, the Irish tramp in London who may have killed a dozen or more people. Of course

-    and we all do a chunk of chat apiece with a sound normal curious local man

-          I grab him a big cold Bulmers bottle and hand him his change. He shakes my hand and tells me he’s after getting seven stables to clean out. He’s not into horses, it’s just a bit of work to keep the show on the road. He tells me the line of work he’s done all his life but I can’t understand a word. It must've been something awful complex. He did it all over the country. He tells me he’ll be 62 on the 18^th^ of April and invites me to his party. There’ll be cans and whiskey and vodka. A man like that might struggle to pull together a large gathering but he's the fifth youngest of twenty-one children so there might yet be a few around to celebrate

-          He’s been an awful alcoholic all his life

-          **Hang around and stuff just happens**

-          **This kind of stuff never happens in bastid restaurants where everyone clumps alone, pretending no one else is there**

Galley Head

-   we'd get grown ups to buy us a f

**Alco in Timoleague**

-          He asks me if I’ll go and buy him a big bottle of cider and hands me  glut of coins. I’m thinking they might have those old 4 pint flaggons we used to buy as teenagers or, as with this poor man, ask people to buy for us in shops.

-          I grab him a big cold Bulmers bottle and hand him his change. He shakes my hand and tells me he’s after getting seven stables to clean out. He’s not into horses, it’s just a bit of work to keep the show on the road. He tells me the line of work he’s done all his life but I can’t understand a word. It must've been something awful complex. He did it all over the country. He tells me he’ll be 62 on the 18^th^ of April and invites me to his party. There’ll be cans and whiskey and vodka. A man like that might struggle to pull together a large gathering but he's the fifth youngest of twenty-one children so there might yet be a few around to celebrate

-          He’s been an awful alcoholic all his life
