---
title: "Mizen Head"
---

To do

-   ADD MAP OF TOWN AGE

-   photos

*There are fourteen lighthouses in The Diocese of Cork and Ross – nowadays known as the sub-county of West Cork – but I don't have the time or organizational skills to take them all on in a clean clockwise motion. So I'm going to take the mathematician's approach and start by solving a bit of the problem and see if the bigger problem becomes clearer after. Or, to take Gumper's advice on doing a PhD, which is applicable to any large project: just get something done every day and it'll all come together eventually. Until I can generate larger gaps in my life, I am stuck doing one-off cycles. This is fine from a cycling viewpoint but I'm not happy about it from a narrative viewpoint. I feellike I'm done with these one day trips and I want to see what would happen to my writing if I were away for three or five or even thirty days at a time. For now though, the geography of West Cork and Kerry lends itself to one-off sniper attacks. There is a handful of finger-like penins ula, each with a lighthouse at its tip, and indeed there are many cycling events which do a loop of a peninsula. The Ring of Kerry cycle is the most famous of these, but there's the Ring of Beara too, and, I was to discover while in Bantry, the Wild Atlantic Mizen Cycle, out to Mizen Head and, for the fitter riders, out to Sheep's Head too.*

------------------------------------------------------------------------

Bantry Square slash piazza is jammers of a Friday for its outdoor bazaar. We wander round with Dudu in the pram and Valentine running around like a fish in water. A Polish fella my age is spinning up candy floss and pulling in four yoyos faster than a Vegas slot machine. I was expecting some kind of cultural awakening, seeing as it's the meeting point for the diffuse cultural hub that is West Cork, a remote sparseland which has been attracting hippies and artists and drop outs for decades, but I get the sense that the influx has peaked and there's a lacka chunfla NRG. This is where the late Ian Bailey sold his poetry and it seems that this realm is not about quality *per se*, but a chance to be yourself and flog a bitta whatevs in order to keep the wolf from the door. A few artists do display their output at the market but the largest stall was selling work clothes for tradespeople. Presumably that is the labour that people do be actually doing round here. Everyone needs their Union fixed and several want their gates painted. But there are not many factories and orifices or any of the other jobs that attract the bulk of the uninspired population. I find a low wall to sit on and listen to three human relics from the old era, aulfla farmers with whiskey noses, tweed blazers, and the thickest of thick accents, like New York Jews who learnt English in a Yiddish-speakng family.

Strewn along the wall and on the ground are pots and pans for sale by a lady calling herself Christina Onassis, a fabulous yapper who lashes out her life story in doublequick time. She was married to a Greek sailor who died at sea, fourteen years ago,[due to a fire on a little boat](https://www.rte.ie/news/2011/0301/298211-bantry/). The last thing she said to him was to nag him about wearing his life jacket. The regret is gushing out of her. Not because he didn't wear his lifejacket but cos she was nagging at him. What she wouldn't do to have him back. She lives up the hill now and every week she sells her pots and crocks and whatever she can get her hands on. The market only charges by the parking space, so she just buys one space for her car and puts her bits and bobs along unrented space on the square. That's the ground below our feet and the low wall opposite. We buy an Arabic flask which looks like the ones my wife would have used as a child. A pot of coffee with cardamom and a bag of sambos whenever they had to take on an entire one-hour drive.

We grab some oily scran at a feed van and I nip in to the tourist office to find out the jacker for the morning. Apparently there's a big cycle on out to Mizen Head and Sheep's Head, exactly the trip I'm hoping to do myself. I was in O'Donovan's cycles this morning getting a tube for my Paul van and they assumed I was in town for that,the [Wild Atlantic Mizen](https://wildatlanticmizencycle.com/) cycle. I reckon it might be fun to piggyback on top of someone else's flow. It should at least be a welcome change from being on the road with me, myself and the Yvonnettes. They tell me that registration is at 7am and the cycle proper starts at 9am.

We stall off and up the hill to the libro where the West Cork Literary Festival has just begun. The atmos gives me the shivers and reminds me of staid events I used to end up at with deadpan weirdos standing about architecture and not a Britney to be seen. I would like to hear Irvine Welsh whenever he's on but you cannae dae it all. I've got books to write myself and a family to love so we all just stall it back to the playground and grab the life story of a madzer Jungwan mammy from Castletownbere who can think of nothing but getting out of West Cork.

PIC OF SUNSET / SUNRISE in EAGLE POINT

We are staying in a delicioso campsite on Eagle Point in Ballylickey, a few clicks north of Bantry, a few clicks south of Glengariff. It is the prettiest place I've ever slept: a perfect mix of land and water, hills and flats, rocks and plants. Big Beara Head is to the north of the bay and gimpy little Sheep's Head is to the south, while Eagle Point is a micro-peninsula at the crook of land where the bay meets the mainland. The campsite is the cleanest and most organized I've seen in Ireland, yet we are essentially wild camping by the water's edge. The jacks are so far away that I use my bike to get there in a reasonable time and we take the car if we've a load of dishes to wash. The place is optimised for a twelve year old with a bike and a hurley, or even a fifteen year old looking for the shift, but the playspaces are too far away for our seven-year-old to bounce back and forth in response to the mood of the group. It feels like we are paying forty-five squids a night for a shower and access to the country we live in, seeing as the land is mostly off limits to landless plebs. The good news is that you can't spend a penny in the campsite. There's no bar, no cafe, no vending machines, no ice creams and no activities. So you don't leak fifty or a hundred squids a day on superfluities.

**0550, Saturday July 13, 2024**

I quietly unzip my way out of the tent, boil up some water on the camping stove and nip down for a quick dip while the water heats up. I grab my gear from the storage tent, lash it on, piece together a few leftovers from last night's dindinz, and then it's time to squeeze in slash out a half-pint of coffee from my AeroPress, an excellent travel companion. I sit down to admire the views across Bantry Bay and to work out my plan for the day. I had originally planned to keep it simple and do a 90k ootenbacher to Sheep's Head, but [The Wild Atlantic Mizen Cycle](https://wildatlanticmizencycle.com/7) has three routes: a 65k trip for beginners, 100k to Mizen Head and back, and 130k toinclude Sheep's Head if I have it in me, although it'd be a good bit further off-road to the lighthouse.

I fix up the bike and cycle the 6k to Bantry along the N71 but it's mercifully quiet at this hour of a Sunday morning. In the tourist office, the main organizer is there and he tells me to just punch on. I can't tell if he's sound of if he has a bit bitter head on him that I haven't paid my way but it's not my fault their cycle is coinciding with mine. It's 44k to Mizen Head, where a biteen of a lighthouse is stationed, but the vaunted visitor centre doesn't open til 10am, so I'll have to dawdle en route, as if I needed encouragement.

I cycle across the empty piazza and follow the thin bay towards both Sheep's Head and Mizen Head. There's a few boats on the water and colourfully painted houses across the way, but the views from the town are curiously unspectacular – for the West of Ireland like – but that's because the land to sea ratio is too high and I feel hemmed in. The graveyard ahead of me, layered into a hill, looks resplendent in the morning sunshine and then it's inland from here to Durrus where Mizen Head and Sheep's Head diverge. 77

Dubhros

-   Israel etc.

I don't take a photo of Sheep's Head in the light but I stop

-   Bantry Geography

    -   few boats in the bay

    -   landscape not spectacular, too contained

    -   as I leave Bantry, the (raised?) graveyard comes to life in the morning sunshine

    -   

-   **Durrow**

    -   Irish spelling at the entrance,

        -   transparent meaning (black ross)

        -   derive all the dialects from the spelling (O'Murchu 1977, need to check), is that actually true?

            -   topic for spelling channel

        -   Gideon & Isrealites (i'm now singing Oh OH, the Israelites by Desmond Dekker)

            -   background <https://genius.com/Desmond-dekker-israelites-lyrics>

-   The Southern Star???

-   Sheep's Head

    -   views of Sheep's Head from the Mizen side are spectacular, with the mid-morning sun shining

    -   didn't stop to take a proper snap of it and I'm raging cos on my way home the land is dark and sky has gone grey.

-   Turn in the road

    -   65k people signpost right, 100k people go left around Mount Gabriel

    -   Cycle East around the mountain ridge, grinding but no steep slopes, see layers of rock

        -   bare, craggy mountain

    -   round the bend and view opens up of Schull and long island

        -   Roaringwater Bay, islands, submerge

        -   good chance to talk about the geography of the landscape

    -   nice descent into the town

    -   recognise the town from Ian Bailey docos & possibly being here

------------------------------------------------------------------------

### **Schull**

Copper Point Lighthouse \
- beacon on Long Island visible from on high\
- Stop to read about ferries, boaty looking person tells me the ferry runs 9-5 from Long Island and people stall over to hike for the day,

-   

    -   mixed interest in yapping,

    -   seem to be sick of curious tourists

-lovely size for a holiday\
\
Make yourself at home\
- Centra is hopping, and it's a big one, the kind where you can pick up fennel. The staff are a mixed bag, possibly stacking shelves to fund a summer at the seaside. One lad looks Algerian, and two lasses sound like Portuguese-tinged Russians, so presumably Ukrainians. The male clientele sport Polo shirts and shorts, and age is marked by sock length. Personality is unmarked in the attire.\
\
I ask one lad if he's out on a boat for the day or what and he says they're off to play golf in Bantry.\
\
The hot counter is loaded up with juicy sasmos and chicken fillets for an army, but my belly frowns so I just grab a coffee, stuff a banana into a plain croissant, and then plonk myself down behind the till on some garden furniture for sale. Three stacked chairs for my Gordon and a glass table for my coffee and scraps of paper, while I listen in to the requests. The Irish Times please, not the blasted Southern Star. Coffee and paracetamol to rinse the blood of last night's gargle.

**Post-Schull**

-   Long Island Beacon

-   Old roads, aulfla and sone out mowing lawn with a tractor

-   bump into a sidetracked cyclist struggling up an unusually steep section. first person i've met on the WAM trip, 12k to Goleen and a good chance for a much-needed natter

-   called Tim Crowley, in runners and a GAA jersey, on a borrowed bike (My kinda guy)

-   We amble along the lumpy terrian & talk cycling & families & breastfeeding v bottle feeding,

    -   3mo & 3yo

-   retiring from football (he still plays 11-a-side) hanging on

-   his descending is poor and reminds me of my earlier days, even though I'm still shite

-   Perfect photo of peninsular coast but I don't stop

**Goleen food stop**

-   stop in GAA club which is slightly out of the village.

    -   Describe cyclists,

        -   chillin on embankment,

        -   the thin faces of the Desmond people, pointy noses and narrow cheeks, esp on the women.

        -   no one is tired yet

        -   Red Cross type peeps round the corner

    -   Food in Gym

        -   sambos + butter

        -   scones + butter (no others)

        -   cake + cinnamon

        -   only two things int he world I can't stand eating and they are lashed all over the free food, so it's obviously a sign to put me off

        -   shite wathery coffee

        -   union is on the other side of the massive clubhouse and while I have no trouble cycling 100k on a bike I take serious umbrage at having to walk 100m to drop a yellow.

        -   \

        -   

    -   Goleen to Mizen

        -   pure delight

        -   a fleet of #realcyclists drives past, humming in unison like an electric car (the disc brakes)

        -   Barley Cove

            -   holiday homes,

            -   punters out for walk / swim / cycle

        -   Crookhaven

            -   miss the lighthouse

            -   

        -   ho\

            -   Mizen\
            -   Ian Bailey etc\]

<!-- -->

-   At one point Tim reckons we are close enough to where poor Sophie Toscan du Plantier was murdered. Tim reckons Ian Bailey was an attention-seeking eejit who didn't do it, as do I.

\
\
\*\*\*\
\
\
I say goodbye to Tim and head for the Mizen visitor centre where I take snaps of the\
\
Mizen visitor centre\
\
- on the wall are photos of lighthouses and in the corner is a map of Ireland, surrounded by like 85 photos taken by John ?Eagleton \[LINK TO PHOTOS\],\
-well arranged, and it's the best resource I've seen for lighthouses\
- lighthouse Pete suggested making a graphic of Irish ones, just like \[THIS\] American one\
- I realise that I've missed Crookhaven. I could have nipped in to see it on my way down, but I didn't realise it was there because I hadn't planned to come to Mizen today.\
- But I have to go back. While this might be top of my list of places to choose to revisit, it's bottom of my list of place that I have to come back to (rephrase), so I gotto go.\
\*\*\*\
\
Mizen tour\
\
Lighthouse keepers' house, with instruments and documents\
- see pictures for deets\
\
Astonishing walk out\
Holy focking moly!\
\
Two parents and their grown up daughter, loosely modelled on a young Sinead O'Connor, discuss great spots for jumping into the water.\
- ballycotton, east cork

-   They are delighted to meet someone with an appreciation of East Cork and I have to say it's something I've come to love. Just knowing places.\
    \
    Malaysian family from Derry, down in Limerick for a teenage swim event, I take a photo of them, Rofl accen\
    \
     \
    \*\*\*\
    (I thought we were doing a doublebackarooney)\
    \
    At a sloped T-junction near Barley Cove stand two stewards sending us left, the shorter way back to Bantry but of course I have to be awkward and turn right, back towards Crookhaven to see an unremarkable lighthouse, and I'm briefly stranded on a tiny island of gravel, while cars from three directions work out how to negotiate this stray obstacle. This is the moment I lose the other cyclists, condemning myself to a 50k return leg on my yet again Tobler. And this is how my life so often has panned out. The obstinate pursuit of obscure goals that no one asked me to do, like a (curious) dog with a phone.\
    -   Examples\
    -   Studying spelling for like a decade\
    -   Analysing data in Apple, like a dog with a bone, to very little avail\
    -   look for other earlier examples.\
    -   doing leaving cert maths in 2/3 year was at least useful, but set a template for, also tried O-Leval and A-level maths but they didn't really know what to do with me so those drifted off. Same\
        \
    -   Lesson is to chart your progress and make sure there is something for others in it. Most of my Apple work went down the Swanney and my spelling thesis will sit on a dusty server, to be read by barely a handful of academics, and I need to turn that knowledge into something useful for people\
    -   The outcome is t\
        \
        \*you will in your Swiss go on your Tobler\*

**Crookhaven lighthouse**

On the flip side, I get to see Barley Cove again and the delightful little beaches around Crookhaven, a charming near-island (?Tombolo) which smiles back at the mainland from a few hundred metres across the water. I'm halfway across the body of land when I realise I'm on the wrong one. The lighthouse sits on a different TOMBOLO. Frustrated, I don't bother checking out the little village, although I might be back to go on a small tour to the Fastnet at some point, as the little tours (i.e. small groups) there are supposedly more informative than the cattle-herding ferries that run from Baltimore, according to the wetser selling tickets in Mizen.\
\
Eventually I find the right tombolo but I'm heading down the wrong road with overgrown ferns and there could easily be a small cult living here unnoticed by the world. I double back and on a road marked private I see the now familiar sturdy walls of CIL, lower than usual, but unmoveable … in that British sort of tradition of us being here …\
\
Blocking my view of the lighthouse is a glassy modern extension, and I can hear a hoover in the background, so I just take a quick snap and bounce. The scenery on the road back to the sleepy village of Goleen recedes in quality, and someone points me to a lifeless café where I sit down for a weak coffee and two sausage rolls in succession, the first one unheated, the second one scalding, but I'm delighted to put something savoury and warm in my Nedser. I'm too wrecked to think or write good notes, so I hit the road as soon as I can. Normally at this point, I'd be looking to recombobulate in a juicer with some scran, then with a clear mind, I'd take on the remaining 40k. Instead I punch on, the short way from Goleen to Durrus, past another huge ridge of rock and back on the north side of Mizen peninsula, looking back at Sheep's Head, which looks a lot less enticing under the clouds, with a clogged brain.\

**Undulating terrain, undulating mind**\
My legs are getting tired and the terrain is annoying me.

-   Flat land does not exist around here, but climbs seldom last long either, so you are never in a rhythm, in your legs or in your head. This is bad for thought because with the constant change your brain does not get to relax.

-   The campsite showers are like that. Every 30 seconds you have to interrupt your flow to press the button to get more water.

-   It's the same with mobile phones, only they are more insidious as they can take out completely out of your current space, rather than just reducing the intensity.

\
\
On the road to Durrus is a WAM sign with a non-ironic smiley face saying only 20k to go. It's possibly another 7k to Ballylickey Pat Rafter, and I'm not in the yumour. As I approach Durrow I come across a few groups of WAMmers but none of them are in a collaborative mood. There's a WAM feed station in Durrow with aulflas and bikes outside but I've no partner to ease the shame of gatecrashing,

so I drop in to a nuclear for a swift one and packa salty peanuts. Unwatched bogball is on the box in the corner. Two more cyclists are in for a late lunch but they're not in the yumour for me. None of these people want to yap. I can't quite put my finger on it but  there's something about being an insider or, worse, a near-insider, that keeps people quiet\[\[??\]\]

-   Few phases then dropper

    -   Check pub name

    -   hundreds of dark bikes outside, plus my bright red 90s laddie

    -   Juicer is rammed and Ireland are playing South Africa. Valentine gets lots among the crowd and we miss Ciaran Frawley knocking over a drop goal to put Ireland within a point of South Africa. IT's the kinda situation where you are asking half the pub if they've seen a chunfla on his Tobler but it seems the locals are unfamiliar with our lingo and cannot help. We find the little rascal and, miraculously, Frawley blasts over another dropper to win the game in the dying seconds. It's hard to know if I'd swap them out for the one he missed agin Toulouse a few weeks back which would have won the Heineken Cup for us. Beating South Africa in South Africa is yuge no matter how often we do it these days.

    -   

-   

-   In the tourist office, the main organizer is there and he tells me to just punch on at my own pace. I can't tell if he's sound of if he has a bit bitter head on him that I haven't paid my way but it's not my fault their cycle is coinciding with mine.\
     \
    \
    Cork people, inane joking.\
    I always feel that this must be how the English look at us. I remember when he was a player thinking that Ronan O'Gara must be thick, just from his accent. And I was shocked that his autobiography - in his early possibly thirties - was so insightful. Eventually you get over that, maybe not his silences or Sean Kelly groans - but it's basic prejudice in action.\
    \
    The people have a withered faces from a life of drink but functional bodies from some resuscitatory cycling.\
    s\
    sland connected to the mainland by a short causeway\
    \
    The scenery diminishes in quality on the way back to Goleen\
    \
    The few chats I have are uninteresting and I understand that these journeys are for finding out how other people live or have lived, rather than meeting people doing the same thing as me, sharing tips and  \
    \
     \[Explain deets\]\
    \
    \*\*\*\

------------------------------------------------------------------------

0550, Saturday July 13, 2024\
\
Running order\
\
Intro\
\
Stall in to\
- Bantry,\
- cycle in to square,\
market, people, charity shops, visit town, Christina, literary festival, poked my head in to the libro and got the shivers, the extraordinary lack of fun in academia,\
- gypsy market in North Cumberland St

Plan before

-   Mizen only or Mizen & sheep's head?

-   Lighthouse opening times

-   WAM route or my own

-   Baby not asleep til 230

-   

**Bantry**

-   types of people

-   street food (tick)

-   workwear

    -   cos for all the jam and cheese you hear about, someone has to fix the leaking rooves

-   bookshop

    -   semi-sorted books with a focus on the the 1980s, presumably the ageing vendor's intellectual heydey

    -   i just want to organize them (to make the shop better)

    -   Sharifa hands me a book of things that look like Ireland

        -   dig out leaf I photoed in Sligo years ago

        -   also the person who collects images of Ireland in the wild

            -   dig out photo of Mercadona in Torrevieja from June 2023

-   

-   feel like I'm on an actual holiday

-   

    -   

------------------------------------------------------------------------

-   \
    \
    taken a campsite recommendation and stalled it out to Eagle Point, a micro-peninsula on the near side of Bantry Bay, with stupendous panoramic views. I had planned to keep it simple and do a handy out-and-backer to Sheep's Head this morning, but it turns out there is a big cycle out to Mizen Head today, and it might be fun to piggyback on top of that, despite the extra distance. The only issue is that Mizen Head

-   Once you stall it out to this large sub-county - the diocese of Cork and Ross, if you will, you can just start picking off lighthouse like a bicycle sniper.

    -   There's like fourteen lighthousey things in West Cork but varying degrees of access means I can't just take them on in a clean clockwise motion. But

    <!-- -->

    -   Shaped like a hand with fingers, so you can pick them off like a sniper

    <!-- -->

<!-- -->

-   EXPLAIN THE GEOGRAPHY
-   d I've decided I want to take on one of its long peninsulae this morning
-   I'm taking on a West Cork peninsula this morning but I'm still not a hundy p whether it's gonna be an 80k out-and-backer to Sheep's Head or a longer trip to the majestic Mizen Head. I'm curled up on this air mattress still trying to finalise my plan

<!-- -->

-   \
     and we've pitched camp at one of the prettiest spots in all of Eagle Point Campsite,\
    \
    There's time enough to savour the view across Bantry Bay which is very different from the coastline I've encountered so far.\
    \
    \
    \
     We are in Eagle Point Campsite\
    \
    . Mostly it's the Beara Peninsula to  the North-West\
    \
    \
    \
    Running order\
    \
    Intro\
    \
    Bags packed,
    -   on the road, fix brakes, raise handlebars, saddle too low but jammed, Vingegaard + Tratnik in gravel stage
    -   Barry in the Union?!,
    -   throw Parkinson's law at the problem\
        520 up, coffee, explain the difficulties of Wild Camping in Eagle Point
    -   Camping
    -   WAM cycle

<!-- -->

-   they charge by the parking space and she only takes up one, but she lays out her pots and crockery along the long stone benches the

-   

used to be married to a Greek sailor.

Christina Onassis

-   Christina Onassismncx\\ETUO\]=#

-   \-

-   \~

    -   a fabulous yapper who lashes out her life story in no time at all.

    -   Her husband died at sea in a fire on a little boat, fourteen years ago, and the last thing she said to him was to nag him about getting the life jacket.

    -   sells pots and crocks.

    -   they charge by the parking space and she only takes up one, but she lays out her pots and crockery along the long stone benches the

    -   bit like the gypsy market on North Cumberland St

    -   

    -   

**Bantry**\
Stall in to Bantry,

-   meeting point for the cycle in tourist office \*on the square(

-   popped in yesterday and the lad told me

WAM cycle

-   

<!-- -->

-   PIC OF SHARIFA, DUDU and VALENTINE with candy floss

-   I had originally planned to keep it simple this morning and do a simple 90k ootenbacher to Sheep's Head, but I was in the bike shop in Bantry yesterday and they told me there is a big cycle out to Mizen Head today,

-    The cycle doesn't start until 9am but yesterday I popped in to Bantry tourist office and they told me that registration starts there at 7.

-   No one here is young and a quick check of the census shows that Bantry has one of the oldest populations in the country. It seems that the West of Ireland is riddled with old people and it's a reminder that very little has ever been done to reverse the outward flow of young working-age people. ADD VIDEO OF MAYO IN THE 80s.

-   

-   **A curiosity of Bantry is that it has one of the oldest populations in the country with the median age being like 44. CHECK CSO**

-   I am lucky enough to sit on a bench with three aulflas yapping away in the thickest of thick accents. CHECK NOTES.

    -   Bray and Sligo

-   

-   The closest thing to this in Dublin is the gypsy bit like the gypsy market on North Cumberland St

<!-- -->

-   The group cycle has three routes, 65k, 100k and 130k. The longest one goes to Mizen Head and then takes on a chunk of Sheep's Head, but doesn't go as far as the lighthouse.

-   your man has a bitter face cos I'm not chucking fifty nicker at the sitch

    -   cycle in to square,\
        market, people, charity shops, visit town, Christina, literary festival, poked my head in to the libro and got the shivers, the extraordinary lack of fun in academia,
    -   gypsy market in North Cumberland St
