---
title: "St John's Point, Donegal"
---

### Intro / start of the end

David David rang me like eighteen months ago to say he was feeling depressed and wanted to go to a lighthouse in Ireland and watch the waves. I was like, it turns our you've called the right man. So he booked a flight from Texas and two nights accommodation in St John's Point Lighthouse cottage. But then my dad got sick in Spain and then David himself wasn't well so we put it on the back burner. He's lodging with us in Wicklow for the month, doing a fellowship in climate change and trying to #pivot within the tech industry, and we've finally reused the credit and booked two nights.

Ben Bulben is orange when I wake up and look out from Farrell's kitchen. He lives near Cartron and I know there's a brilliant viewing point round the corner, so I lash on my gear and leg it out the door.

-   so I lash on my gear and am ready to go in three minutes but it's already too late. I gave Elske a right shock cpos I shouted 'fuck' and she's probably not used to that kind of commotion, They run a mellow ship and dinner last night was the first time I hung out with their younger kids now aged six and eleven.

-   They live beside Cartron so I just nipped round the corner near the micro-village and had a good look at the orange light behind NAME MOUNTAIN. I always forget Ben Bulben, unlike isolated Knocknarea, has multiple partners although none of them are geometricrally perfect enough to be a graphic describing the path of various phenomena. We are all used to S-curves, with a slow start, sudden fast uptake before levelling off, but usually the graphic stops there. Ben Bulben also contains the plateau on top.

**Route**

I haven't planned my route exactly and I need to be careful I don't get swallowed up by the 'gaffed' coast. It's 95k as the bogger drives fropm SLigo to St Joh'n's Point Lighthouse which lives down the longest skinniest little strip of a peninsula on the near side of Killibegs Bay. But the N15 is a killler of a a road so my aim is to hug the coast and dodge the Jammers.

Sligo coastline access

-   Sligo town sits on a bay-within-a-bay, and as a result it has more coastline nearby it at

-   labial, orchid shape

    -   to the south is Ballisodare Bay / feeing off to the south, sligo & Mayo ) with its craggy hills whiose outline you can find on a logo of Carrow Coffee

    -   more famously youy've got Strandhikll Peninsula, best known as a surger's beach, and Rosses Point with it enormous beach for swimming

    -   I'll be cycling there another day coming from Ballisodare / South Sligo / Mayo

    -   But the northern chunk of coastline is lesser known & it's wher i'm going today

    -   

### **Spin 103.Yeats Country**

-   I stop off at the chuch in Drumcliff where William Butler Yeats, the great poet, was buried. Jesus, he was a great man for the output. Got a bit done every day for fifty years and came out with a never-ending output of ever simpler poems. Even I can enjoy his poems. I could never follow what poets are banging on about with their lilies and daffodils and images. It was always images. Talk about the imagery in the poem. I can't imagine anything in my head bar shapes. I've got to see it. I must go on a Yeats tour of sligo. I popped down to the old Lake Isle of Inisfree one time and I could actually hear the lake water lapping. Right here, *Under bare Ben Bulben / In Drumcliff yard Yeats is laid*.

-   #With Yeats you can actually come ad

-   Yeats United football club

    -   cultural legacy absorbed by the locals

-   Carney

    -   stop in shop but it's closed now from 8-9 even though it has already been open. A Welsh lad in a Hiace (yup) says she's gone to open her other shop nearby

-   Lissadell

    -   never visited, closed now for September, lack of staff

    -   crappy bit of coastline tbf

-   Beach lady

    -   first swim of the year, uncle a shipbuilder, interest in ships, surprisingly excited though her uncle turns out to be a shipbuilder

    -   sends me down to Roghly - pron like Rockly - range of spellings on noticeboard

    -   small harbour, little headland, isthmus prob not a tombolo, not much life on it, no shop etc. no crookhaven say

-   Mullaghmore

    -   change of landscape, very different, sheep now only, Sligo full of good cattle land

        -   trees dead or leaves dying for autumn

        -   random isolated random patch

        -   house located on high, must be fierce windy up there, scene of a horror story

    -   Sedimentary rock, large beach, shallow harbour, well built, made for small boats only, tiny gap

-   Coast of Leitrim

    -   Ask lady for directions, accent has a thick chunk of Nordy but she says she's not a local but from Carrick-on-Shannon

    -   Brutal land, no beach, few stones in the sea and only cos the tide is out

    -   don't think you could even have a walk on the rocks by the water.

    -   <https://www.leitrimobserver.ie/news/home/1355754/put-treasured-coastal-village-on-the-map.html> Put Tullaghan on the map

    -   feeds into outskirts of Bundoran

-   Living in this climate

    -   no pain, no gain,

    -   rainfall stats & sunshine hours,

    -   thought about living here but numbers like that are horroof

    -   

-   I have a deep love of word stress and have spent a chunk of my life studying it and teaching it. The passion theoretically extends to poetic verse but somehow, amidst my degrees in literature and linguistics, no one ever taught me about the hashtag rules of verse, bar my Latin teacher in secondary school. In the English-speaking world, the two subjects split apart and both of them crept up their respective Gordon in their own ways. Literature studies became obsessed with culture and all the subject matter that falls into the culture wars now. Everyone forgot that literature was about beauty of expression and havin' a giraffe. Meanwhile, linguistics focussed on speech only because writing was seen as too contrived, not really 'natural language', useful only for studying language in the past. Now you could record speech and analyse the bejaysus out of it. Of course, they threw the baby out with the bathwater, forgot about literature and, again, the inherent beauty of well-constructed language. Poetry wasn't part of the program and thus the patterns of poetry were completely forgotten about. And yet the study of speech eventually worked out how words are stressed and how metre acts across phrases. The end result is that the two fields of study are ready to overlap but, when I moved out of academia, it hadn't yet been done.

    -   metre within words and across phrases

    -   known as Pottie because he was a bit of a space cadet

-   You didn't study poetry so you didn't need to study the patterns inside the poetry. Hence no study of verse.

-   People eventually began to care about stress in words and phrases but they

-   ve always wanted to visualized

## **Fundoran**

-   The coast of Leitrim feeds into the outskirts of Bundoran and it's a relief to be back in a large settlement, especially this one which has been optimized for holiday-making, with

    -   wI follow the road straight to the main beach which is very close to the town centre. In

    -   I head straight to the beach in Bundoran. It's a really

The tide is out but a huge knee-high pool survives and it's the perfect spot for a bathe and a blether. As I'm getting dressed, a dog is running and barker too close to an increasingly frightened lady and she's trying to tell the owner to put him on a leash, but yer man is being all *what are you on about?* I mosey over in case it kicks off but the dog finds something else to bark at and I get yapping to her. She's more than happy to give me a quick blast of her life story, or at least the story of her love life, working backwards from this trip.

### Hundred nicker holier

-   She turns out to be a Cyavan Gyal and, fittingly, she gives me an exact breakdown of the price of her little holiday here. The hostel, of all places, was only fifty euro. A private room. So she called her friend from Sligo to go halves on the craic, so they only paid seventy between them for the room, a double and a single bed. Breakfast included too. Not a fry up, mind, but toast and coffee and fruit. I told her it's a barg, the cheapest room in Ireland, and she said the dinner in the pub was eighteen euro and that was enough for her, with a full plate of veg and potatoes and lovely meat. There was some lovely country music for the older people and it was great because the pubs don't have any craic like they used to as the young wans are all on their phones. With the two gin and tonics –plenty – the whole trip barely came to a hundred euro, as the bus was free now that she's over the magic age.

### **Sure we all partied**

-   She had cancer in the early 2000s and got over it but she's never worked since. Hated it. Used to work in a factory before that and couldn't go back. So she moved to Malta to get better and she could do that then because they just put your disability payment in your bank account. That was the Celtic Tiger all over. I remember it well myself. Everybody had a piece of the pie back then, and the mood was great. I spent the summer of 2007 festival hopping around Europe, coming home once a month to sign on. Benicassim, Sziget, Edinburgh. I was in the Gelert Baths in Budapest on the blower to the Dole Office, giving them all that cos they hadn't lashed my cash into my account. I only found out the other dat that that was the venue for a massiv orgy

-   Every summer in my dad's shop the customers would have more and more cash and load up their vans with animal feed before jetting off to the sun. This was an era when college students got twenty quid an hour to hand out free booze promotions.

-   Then in the 2007, I was twenty-three and doing a 'six-month' maternity cover in Alexandra College, teaching maths. It was from April to December, and the six months didn't include good ol' June, July and August, so I went on tour around Europe, mostly festival hopping, with my Morocc'n'roll money being sent straight to my bank account. The only catch was that I had to come home once a month to sign on, so I had to keep within Ryanair's ambit. I did two weeks of island hopping in Croatia, a week in Sarajevo, home for a bit, off to Benicassim for a week, a festival so intense that our tag line was *We're not here to have fun*. About twenty of us went to the Sziget festival in Hungary for a week and I finished up at the Edinburgh festival, drinking Turbo Shandies to squeeze out the last of my party energy.

-   I still have and use the same rucksack, with The Brendan Voyage written on it, along with the names of the countries I visited, in their own language of course. *España, Hrvatska*, *Magyayorszag*. It was tough getting back to the algebra after that.

-   People often remember the Celtic Tiger as a ridonculous era where taxi drivers would own three properties, including one in Bulgaria. But beyond the scarlifying opulence and excess, there was a basic quality of living for a lot more people. Students went to college for almost nothing and could fend for themselves, minus the maybe rent. Grown-ups could buy a home and plan a family. Ageing parents didn't have to house their grown up children who could go out and live a little. I don't know if elderly people's lives have changed that much although I wouldn't be surprised if more of them do full-time childcare now for their grandkids.

-   We've lost so much of that

-   Sometimes we think of the Celtic Tiger era as something unreal and, in many ways it was, but the truth is that it was the only period in Irish history when most people were materially comfortable and could really enjoy their lives. It's tragic that we've moved into an era now where

-   Maybe it was just a better time because phones allowed us to stay connected to people but not connected to the Jimi Internet.

## Last bit

There's still 68k of cycling to go and I'm gonna be much later than expected. I call my wife and she's having a conniption in the car, still thirty minutes from Donegal. I can't believe she's gone that way. I told her to add fifteen minutes to the trip and go via Sligo and Bundoran – we're talking four hours versus four hours and fifteen – and that way they can all have a nice trip to the beach before the final push to the lighthouse. But of course she's just put on Google Maps and followed the bastard thing. I'm thinking, I can at least make it to Donegal and then finish off the trip another day but I only get as far as Ballyshannon when she's ringing me again. I'm on the N15 at this stage, crossing a four-lane bridge with no hard shoulder, and a lorry hurtles past me two feet away. I'm shaking, the bike is shaking, and it feels like the bridge is shaking, and I just take the L and decide to pull in when I can and let her pick me up. I'm really pissed off with her but it doesn't matter because I'm pissed off with myself. I spent too much time faffing about along the Sligo coast and forgot that the core priority is to cycle to lighthouses, with the coast being a secondary bonus. It'll be a good lesson here out west where the coastline is much more jagged and difficult to follow. I should have given her a specific time to meet at the lighthouse – say 5pm – and then I'd've worked within my limits.

I take the wheels off my bike, shove the frame into the car, between the kids and the front seats, and I can at least chillax now in the driving seat as she's understandably done enough driving. We grab supplies in Donegal Town, where I listen in to the ageing ladies yapping at the till counter, amazed at how much the accent can change in such a short space. The till lady sounds local and the customer is similar but speaks as slowly as they do in Fermanagh.

The drive from Ballyshannon to Donegal and towards Killybegs is one of the worst cycles in the entire country, and I'm secretly delighted to skip it. It's a fast-paced main road the whole way, noisy with cars, windy with width, and often having no space for a bike. We turn off after Dunkineely and drive the long slow ten k to the lighthouse with the same vibe as the bus home after losing a football match, and we settle down for a quiet night in one of the lighthouse cottages.

### Loop around St John's Peninsula

I woke up feel worthless and having failed in my mission. No one was happy yesterday and the kids didn't even get a run out on the lovely beach. By the time we had checked out the lighthouse and surroundings, the evening breeze had kicked off and it was too chilly for building sandcastles.

I'm not particularly upset about missing the 50k along the main roads but I do want to see this peninsula while I'm here, otherwise I'll be left with a 20k Ootenbach job the next time I'm passing, on my way to Rothlin's Island presumably. So I get out of the Margaret, put the bike back together, get a load of oil on my civvies and force myself to start cycling. The second day is always miserable until you are up and running and cycling cures cycling pain so I know I just have to do it.

It's odd to be cycling *away* from the lighthouse but it already feels homely. The lighthouse stands on a mid-sized headland away from the main peninsula. It's lumpy, grassy and treeless out here, with a skinny lane that was clearly built by the Commissioner of Irish Lights.

It's interesting to live the. The tall walls keep the wind out and toddlers in, and the there are neat low walls separating one cottage's garden grass patch from the other's. It's great to watch the kids run about and reimagine all the previous children who lived here before, creating entertainment for themselves. You would need a fleet of kids to keep yourselves occupied out here but it's doable.

St John's Point

-   treeless, grassy headland, connected to main peninsula by a tiny isthmus beach, probably a tombolo

-   sheep mostly but some hay being baled in parts

-   handweaving, old cottage thatched,

-   sign for toxic land

-   
